// Code generated by ent, DO NOT EDIT.

package postsentiment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the postsentiment type in the database.
	Label = "post_sentiment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPostID holds the string denoting the post_id field in the database.
	FieldPostID = "post_id"
	// FieldSentimentTag holds the string denoting the sentiment_tag field in the database.
	FieldSentimentTag = "sentiment_tag"
	// FieldPositivityScore holds the string denoting the positivity_score field in the database.
	FieldPositivityScore = "positivity_score"
	// FieldPrimaryTopic holds the string denoting the primary_topic field in the database.
	FieldPrimaryTopic = "primary_topic"
	// FieldScoringStatus holds the string denoting the scoring_status field in the database.
	FieldScoringStatus = "scoring_status"
	// FieldRankScore holds the string denoting the rank_score field in the database.
	FieldRankScore = "rank_score"
	// EdgePost holds the string denoting the post edge name in mutations.
	EdgePost = "post"
	// Table holds the table name of the postsentiment in the database.
	Table = "post_sentiments"
	// PostTable is the table that holds the post relation/edge.
	PostTable = "post_sentiments"
	// PostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostInverseTable = "posts"
	// PostColumn is the table column denoting the post relation/edge.
	PostColumn = "post_id"
)

// Columns holds all SQL columns for postsentiment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPostID,
	FieldSentimentTag,
	FieldPositivityScore,
	FieldPrimaryTopic,
	FieldScoringStatus,
	FieldRankScore,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultRankScore holds the default value on creation for the "rank_score" field.
	DefaultRankScore float64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// ScoringStatus defines the type for the "scoring_status" enum field.
type ScoringStatus string

// ScoringStatusUnscored is the default value of the ScoringStatus enum.
const DefaultScoringStatus = ScoringStatusUnscored

// ScoringStatus values.
const (
	ScoringStatusUnscored ScoringStatus = "unscored"
	ScoringStatusScored   ScoringStatus = "scored"
	ScoringStatusFailed   ScoringStatus = "failed"
)

func (ss ScoringStatus) String() string {
	return string(ss)
}

// ScoringStatusValidator is a validator for the "scoring_status" field enum values. It is called by the builders before save.
func ScoringStatusValidator(ss ScoringStatus) error {
	switch ss {
	case ScoringStatusUnscored, ScoringStatusScored, ScoringStatusFailed:
		return nil
	default:
		return fmt.Errorf("postsentiment: invalid enum value for scoring_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the PostSentiment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPostID orders the results by the post_id field.
func ByPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostID, opts...).ToFunc()
}

// BySentimentTag orders the results by the sentiment_tag field.
func BySentimentTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSentimentTag, opts...).ToFunc()
}

// ByPositivityScore orders the results by the positivity_score field.
func ByPositivityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPositivityScore, opts...).ToFunc()
}

// ByPrimaryTopic orders the results by the primary_topic field.
func ByPrimaryTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryTopic, opts...).ToFunc()
}

// ByScoringStatus orders the results by the scoring_status field.
func ByScoringStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoringStatus, opts...).ToFunc()
}

// ByRankScore orders the results by the rank_score field.
func ByRankScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRankScore, opts...).ToFunc()
}

// ByPostField orders the results by post field.
func ByPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostStep(), sql.OrderByField(field, opts...))
	}
}
func newPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, PostTable, PostColumn),
	)
}
