// Code generated by ent, DO NOT EDIT.

package postsentiment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldUpdatedAt, v))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldPostID, v))
}

// SentimentTag applies equality check predicate on the "sentiment_tag" field. It's identical to SentimentTagEQ.
func SentimentTag(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldSentimentTag, v))
}

// PositivityScore applies equality check predicate on the "positivity_score" field. It's identical to PositivityScoreEQ.
func PositivityScore(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldPositivityScore, v))
}

// PrimaryTopic applies equality check predicate on the "primary_topic" field. It's identical to PrimaryTopicEQ.
func PrimaryTopic(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldPrimaryTopic, v))
}

// RankScore applies equality check predicate on the "rank_score" field. It's identical to RankScoreEQ.
func RankScore(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldRankScore, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldUpdatedAt, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldPostID, v))
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldPostID, v))
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldPostID, v))
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v xid.ID) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldPostID, v))
}

// PostIDContains applies the Contains predicate on the "post_id" field.
func PostIDContains(v xid.ID) predicate.PostSentiment {
	vc := v.String()
	return predicate.PostSentiment(sql.FieldContains(FieldPostID, vc))
}

// PostIDHasPrefix applies the HasPrefix predicate on the "post_id" field.
func PostIDHasPrefix(v xid.ID) predicate.PostSentiment {
	vc := v.String()
	return predicate.PostSentiment(sql.FieldHasPrefix(FieldPostID, vc))
}

// PostIDHasSuffix applies the HasSuffix predicate on the "post_id" field.
func PostIDHasSuffix(v xid.ID) predicate.PostSentiment {
	vc := v.String()
	return predicate.PostSentiment(sql.FieldHasSuffix(FieldPostID, vc))
}

// PostIDEqualFold applies the EqualFold predicate on the "post_id" field.
func PostIDEqualFold(v xid.ID) predicate.PostSentiment {
	vc := v.String()
	return predicate.PostSentiment(sql.FieldEqualFold(FieldPostID, vc))
}

// PostIDContainsFold applies the ContainsFold predicate on the "post_id" field.
func PostIDContainsFold(v xid.ID) predicate.PostSentiment {
	vc := v.String()
	return predicate.PostSentiment(sql.FieldContainsFold(FieldPostID, vc))
}

// SentimentTagEQ applies the EQ predicate on the "sentiment_tag" field.
func SentimentTagEQ(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldSentimentTag, v))
}

// SentimentTagNEQ applies the NEQ predicate on the "sentiment_tag" field.
func SentimentTagNEQ(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldSentimentTag, v))
}

// SentimentTagIn applies the In predicate on the "sentiment_tag" field.
func SentimentTagIn(vs ...string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldSentimentTag, vs...))
}

// SentimentTagNotIn applies the NotIn predicate on the "sentiment_tag" field.
func SentimentTagNotIn(vs ...string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldSentimentTag, vs...))
}

// SentimentTagGT applies the GT predicate on the "sentiment_tag" field.
func SentimentTagGT(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldSentimentTag, v))
}

// SentimentTagGTE applies the GTE predicate on the "sentiment_tag" field.
func SentimentTagGTE(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldSentimentTag, v))
}

// SentimentTagLT applies the LT predicate on the "sentiment_tag" field.
func SentimentTagLT(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldSentimentTag, v))
}

// SentimentTagLTE applies the LTE predicate on the "sentiment_tag" field.
func SentimentTagLTE(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldSentimentTag, v))
}

// SentimentTagContains applies the Contains predicate on the "sentiment_tag" field.
func SentimentTagContains(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldContains(FieldSentimentTag, v))
}

// SentimentTagHasPrefix applies the HasPrefix predicate on the "sentiment_tag" field.
func SentimentTagHasPrefix(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldHasPrefix(FieldSentimentTag, v))
}

// SentimentTagHasSuffix applies the HasSuffix predicate on the "sentiment_tag" field.
func SentimentTagHasSuffix(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldHasSuffix(FieldSentimentTag, v))
}

// SentimentTagIsNil applies the IsNil predicate on the "sentiment_tag" field.
func SentimentTagIsNil() predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIsNull(FieldSentimentTag))
}

// SentimentTagNotNil applies the NotNil predicate on the "sentiment_tag" field.
func SentimentTagNotNil() predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotNull(FieldSentimentTag))
}

// SentimentTagEqualFold applies the EqualFold predicate on the "sentiment_tag" field.
func SentimentTagEqualFold(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEqualFold(FieldSentimentTag, v))
}

// SentimentTagContainsFold applies the ContainsFold predicate on the "sentiment_tag" field.
func SentimentTagContainsFold(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldContainsFold(FieldSentimentTag, v))
}

// PositivityScoreEQ applies the EQ predicate on the "positivity_score" field.
func PositivityScoreEQ(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldPositivityScore, v))
}

// PositivityScoreNEQ applies the NEQ predicate on the "positivity_score" field.
func PositivityScoreNEQ(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldPositivityScore, v))
}

// PositivityScoreIn applies the In predicate on the "positivity_score" field.
func PositivityScoreIn(vs ...int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldPositivityScore, vs...))
}

// PositivityScoreNotIn applies the NotIn predicate on the "positivity_score" field.
func PositivityScoreNotIn(vs ...int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldPositivityScore, vs...))
}

// PositivityScoreGT applies the GT predicate on the "positivity_score" field.
func PositivityScoreGT(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldPositivityScore, v))
}

// PositivityScoreGTE applies the GTE predicate on the "positivity_score" field.
func PositivityScoreGTE(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldPositivityScore, v))
}

// PositivityScoreLT applies the LT predicate on the "positivity_score" field.
func PositivityScoreLT(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldPositivityScore, v))
}

// PositivityScoreLTE applies the LTE predicate on the "positivity_score" field.
func PositivityScoreLTE(v int) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldPositivityScore, v))
}

// PositivityScoreIsNil applies the IsNil predicate on the "positivity_score" field.
func PositivityScoreIsNil() predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIsNull(FieldPositivityScore))
}

// PositivityScoreNotNil applies the NotNil predicate on the "positivity_score" field.
func PositivityScoreNotNil() predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotNull(FieldPositivityScore))
}

// PrimaryTopicEQ applies the EQ predicate on the "primary_topic" field.
func PrimaryTopicEQ(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldPrimaryTopic, v))
}

// PrimaryTopicNEQ applies the NEQ predicate on the "primary_topic" field.
func PrimaryTopicNEQ(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldPrimaryTopic, v))
}

// PrimaryTopicIn applies the In predicate on the "primary_topic" field.
func PrimaryTopicIn(vs ...string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldPrimaryTopic, vs...))
}

// PrimaryTopicNotIn applies the NotIn predicate on the "primary_topic" field.
func PrimaryTopicNotIn(vs ...string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldPrimaryTopic, vs...))
}

// PrimaryTopicGT applies the GT predicate on the "primary_topic" field.
func PrimaryTopicGT(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldPrimaryTopic, v))
}

// PrimaryTopicGTE applies the GTE predicate on the "primary_topic" field.
func PrimaryTopicGTE(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldPrimaryTopic, v))
}

// PrimaryTopicLT applies the LT predicate on the "primary_topic" field.
func PrimaryTopicLT(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldPrimaryTopic, v))
}

// PrimaryTopicLTE applies the LTE predicate on the "primary_topic" field.
func PrimaryTopicLTE(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldPrimaryTopic, v))
}

// PrimaryTopicContains applies the Contains predicate on the "primary_topic" field.
func PrimaryTopicContains(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldContains(FieldPrimaryTopic, v))
}

// PrimaryTopicHasPrefix applies the HasPrefix predicate on the "primary_topic" field.
func PrimaryTopicHasPrefix(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldHasPrefix(FieldPrimaryTopic, v))
}

// PrimaryTopicHasSuffix applies the HasSuffix predicate on the "primary_topic" field.
func PrimaryTopicHasSuffix(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldHasSuffix(FieldPrimaryTopic, v))
}

// PrimaryTopicIsNil applies the IsNil predicate on the "primary_topic" field.
func PrimaryTopicIsNil() predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIsNull(FieldPrimaryTopic))
}

// PrimaryTopicNotNil applies the NotNil predicate on the "primary_topic" field.
func PrimaryTopicNotNil() predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotNull(FieldPrimaryTopic))
}

// PrimaryTopicEqualFold applies the EqualFold predicate on the "primary_topic" field.
func PrimaryTopicEqualFold(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEqualFold(FieldPrimaryTopic, v))
}

// PrimaryTopicContainsFold applies the ContainsFold predicate on the "primary_topic" field.
func PrimaryTopicContainsFold(v string) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldContainsFold(FieldPrimaryTopic, v))
}

// ScoringStatusEQ applies the EQ predicate on the "scoring_status" field.
func ScoringStatusEQ(v ScoringStatus) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldScoringStatus, v))
}

// ScoringStatusNEQ applies the NEQ predicate on the "scoring_status" field.
func ScoringStatusNEQ(v ScoringStatus) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldScoringStatus, v))
}

// ScoringStatusIn applies the In predicate on the "scoring_status" field.
func ScoringStatusIn(vs ...ScoringStatus) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldScoringStatus, vs...))
}

// ScoringStatusNotIn applies the NotIn predicate on the "scoring_status" field.
func ScoringStatusNotIn(vs ...ScoringStatus) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldScoringStatus, vs...))
}

// RankScoreEQ applies the EQ predicate on the "rank_score" field.
func RankScoreEQ(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldEQ(FieldRankScore, v))
}

// RankScoreNEQ applies the NEQ predicate on the "rank_score" field.
func RankScoreNEQ(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNEQ(FieldRankScore, v))
}

// RankScoreIn applies the In predicate on the "rank_score" field.
func RankScoreIn(vs ...float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldIn(FieldRankScore, vs...))
}

// RankScoreNotIn applies the NotIn predicate on the "rank_score" field.
func RankScoreNotIn(vs ...float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldNotIn(FieldRankScore, vs...))
}

// RankScoreGT applies the GT predicate on the "rank_score" field.
func RankScoreGT(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGT(FieldRankScore, v))
}

// RankScoreGTE applies the GTE predicate on the "rank_score" field.
func RankScoreGTE(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldGTE(FieldRankScore, v))
}

// RankScoreLT applies the LT predicate on the "rank_score" field.
func RankScoreLT(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLT(FieldRankScore, v))
}

// RankScoreLTE applies the LTE predicate on the "rank_score" field.
func RankScoreLTE(v float64) predicate.PostSentiment {
	return predicate.PostSentiment(sql.FieldLTE(FieldRankScore, v))
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.PostSentiment {
	return predicate.PostSentiment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.PostSentiment {
	return predicate.PostSentiment(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PostSentiment) predicate.PostSentiment {
	return predicate.PostSentiment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PostSentiment) predicate.PostSentiment {
	return predicate.PostSentiment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PostSentiment) predicate.PostSentiment {
	return predicate.PostSentiment(sql.NotPredicates(p))
}
