// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/adminreplytime"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// AdminReplyTimeUpdate is the builder for updating AdminReplyTime entities.
type AdminReplyTimeUpdate struct {
	config
	hooks     []Hook
	mutation  *AdminReplyTimeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AdminReplyTimeUpdate builder.
func (_u *AdminReplyTimeUpdate) Where(ps ...predicate.AdminReplyTime) *AdminReplyTimeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserPostID sets the "user_post_id" field.
func (_u *AdminReplyTimeUpdate) SetUserPostID(v xid.ID) *AdminReplyTimeUpdate {
	_u.mutation.SetUserPostID(v)
	return _u
}

// SetNillableUserPostID sets the "user_post_id" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableUserPostID(v *xid.ID) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetUserPostID(*v)
	}
	return _u
}

// SetAdminPostID sets the "admin_post_id" field.
func (_u *AdminReplyTimeUpdate) SetAdminPostID(v xid.ID) *AdminReplyTimeUpdate {
	_u.mutation.SetAdminPostID(v)
	return _u
}

// SetNillableAdminPostID sets the "admin_post_id" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableAdminPostID(v *xid.ID) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetAdminPostID(*v)
	}
	return _u
}

// SetUserPostTime sets the "user_post_time" field.
func (_u *AdminReplyTimeUpdate) SetUserPostTime(v time.Time) *AdminReplyTimeUpdate {
	_u.mutation.SetUserPostTime(v)
	return _u
}

// SetNillableUserPostTime sets the "user_post_time" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableUserPostTime(v *time.Time) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetUserPostTime(*v)
	}
	return _u
}

// SetAdminPostTime sets the "admin_post_time" field.
func (_u *AdminReplyTimeUpdate) SetAdminPostTime(v time.Time) *AdminReplyTimeUpdate {
	_u.mutation.SetAdminPostTime(v)
	return _u
}

// SetNillableAdminPostTime sets the "admin_post_time" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableAdminPostTime(v *time.Time) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetAdminPostTime(*v)
	}
	return _u
}

// SetAdminAccountID sets the "admin_account_id" field.
func (_u *AdminReplyTimeUpdate) SetAdminAccountID(v xid.ID) *AdminReplyTimeUpdate {
	_u.mutation.SetAdminAccountID(v)
	return _u
}

// SetNillableAdminAccountID sets the "admin_account_id" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableAdminAccountID(v *xid.ID) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetAdminAccountID(*v)
	}
	return _u
}

// SetAdminHandle sets the "admin_handle" field.
func (_u *AdminReplyTimeUpdate) SetAdminHandle(v string) *AdminReplyTimeUpdate {
	_u.mutation.SetAdminHandle(v)
	return _u
}

// SetNillableAdminHandle sets the "admin_handle" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableAdminHandle(v *string) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetAdminHandle(*v)
	}
	return _u
}

// SetTimeDifferenceSeconds sets the "time_difference_seconds" field.
func (_u *AdminReplyTimeUpdate) SetTimeDifferenceSeconds(v int64) *AdminReplyTimeUpdate {
	_u.mutation.ResetTimeDifferenceSeconds()
	_u.mutation.SetTimeDifferenceSeconds(v)
	return _u
}

// SetNillableTimeDifferenceSeconds sets the "time_difference_seconds" field if the given value is not nil.
func (_u *AdminReplyTimeUpdate) SetNillableTimeDifferenceSeconds(v *int64) *AdminReplyTimeUpdate {
	if v != nil {
		_u.SetTimeDifferenceSeconds(*v)
	}
	return _u
}

// AddTimeDifferenceSeconds adds value to the "time_difference_seconds" field.
func (_u *AdminReplyTimeUpdate) AddTimeDifferenceSeconds(v int64) *AdminReplyTimeUpdate {
	_u.mutation.AddTimeDifferenceSeconds(v)
	return _u
}

// SetUserPost sets the "user_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdate) SetUserPost(v *Post) *AdminReplyTimeUpdate {
	return _u.SetUserPostID(v.ID)
}

// SetAdminPost sets the "admin_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdate) SetAdminPost(v *Post) *AdminReplyTimeUpdate {
	return _u.SetAdminPostID(v.ID)
}

// SetAdminAccount sets the "admin_account" edge to the Account entity.
func (_u *AdminReplyTimeUpdate) SetAdminAccount(v *Account) *AdminReplyTimeUpdate {
	return _u.SetAdminAccountID(v.ID)
}

// Mutation returns the AdminReplyTimeMutation object of the builder.
func (_u *AdminReplyTimeUpdate) Mutation() *AdminReplyTimeMutation {
	return _u.mutation
}

// ClearUserPost clears the "user_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdate) ClearUserPost() *AdminReplyTimeUpdate {
	_u.mutation.ClearUserPost()
	return _u
}

// ClearAdminPost clears the "admin_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdate) ClearAdminPost() *AdminReplyTimeUpdate {
	_u.mutation.ClearAdminPost()
	return _u
}

// ClearAdminAccount clears the "admin_account" edge to the Account entity.
func (_u *AdminReplyTimeUpdate) ClearAdminAccount() *AdminReplyTimeUpdate {
	_u.mutation.ClearAdminAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminReplyTimeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminReplyTimeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminReplyTimeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminReplyTimeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminReplyTimeUpdate) check() error {
	if _u.mutation.UserPostCleared() && len(_u.mutation.UserPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminReplyTime.user_post"`)
	}
	if _u.mutation.AdminPostCleared() && len(_u.mutation.AdminPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminReplyTime.admin_post"`)
	}
	if _u.mutation.AdminAccountCleared() && len(_u.mutation.AdminAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminReplyTime.admin_account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AdminReplyTimeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AdminReplyTimeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AdminReplyTimeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminreplytime.Table, adminreplytime.Columns, sqlgraph.NewFieldSpec(adminreplytime.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserPostTime(); ok {
		_spec.SetField(adminreplytime.FieldUserPostTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AdminPostTime(); ok {
		_spec.SetField(adminreplytime.FieldAdminPostTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AdminHandle(); ok {
		_spec.SetField(adminreplytime.FieldAdminHandle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TimeDifferenceSeconds(); ok {
		_spec.SetField(adminreplytime.FieldTimeDifferenceSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeDifferenceSeconds(); ok {
		_spec.AddField(adminreplytime.FieldTimeDifferenceSeconds, field.TypeInt64, value)
	}
	if _u.mutation.UserPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.UserPostTable,
			Columns: []string{adminreplytime.UserPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.UserPostTable,
			Columns: []string{adminreplytime.UserPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminPostTable,
			Columns: []string{adminreplytime.AdminPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminPostTable,
			Columns: []string{adminreplytime.AdminPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminAccountTable,
			Columns: []string{adminreplytime.AdminAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminAccountTable,
			Columns: []string{adminreplytime.AdminAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminreplytime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminReplyTimeUpdateOne is the builder for updating a single AdminReplyTime entity.
type AdminReplyTimeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AdminReplyTimeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserPostID sets the "user_post_id" field.
func (_u *AdminReplyTimeUpdateOne) SetUserPostID(v xid.ID) *AdminReplyTimeUpdateOne {
	_u.mutation.SetUserPostID(v)
	return _u
}

// SetNillableUserPostID sets the "user_post_id" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableUserPostID(v *xid.ID) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetUserPostID(*v)
	}
	return _u
}

// SetAdminPostID sets the "admin_post_id" field.
func (_u *AdminReplyTimeUpdateOne) SetAdminPostID(v xid.ID) *AdminReplyTimeUpdateOne {
	_u.mutation.SetAdminPostID(v)
	return _u
}

// SetNillableAdminPostID sets the "admin_post_id" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableAdminPostID(v *xid.ID) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetAdminPostID(*v)
	}
	return _u
}

// SetUserPostTime sets the "user_post_time" field.
func (_u *AdminReplyTimeUpdateOne) SetUserPostTime(v time.Time) *AdminReplyTimeUpdateOne {
	_u.mutation.SetUserPostTime(v)
	return _u
}

// SetNillableUserPostTime sets the "user_post_time" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableUserPostTime(v *time.Time) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetUserPostTime(*v)
	}
	return _u
}

// SetAdminPostTime sets the "admin_post_time" field.
func (_u *AdminReplyTimeUpdateOne) SetAdminPostTime(v time.Time) *AdminReplyTimeUpdateOne {
	_u.mutation.SetAdminPostTime(v)
	return _u
}

// SetNillableAdminPostTime sets the "admin_post_time" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableAdminPostTime(v *time.Time) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetAdminPostTime(*v)
	}
	return _u
}

// SetAdminAccountID sets the "admin_account_id" field.
func (_u *AdminReplyTimeUpdateOne) SetAdminAccountID(v xid.ID) *AdminReplyTimeUpdateOne {
	_u.mutation.SetAdminAccountID(v)
	return _u
}

// SetNillableAdminAccountID sets the "admin_account_id" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableAdminAccountID(v *xid.ID) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetAdminAccountID(*v)
	}
	return _u
}

// SetAdminHandle sets the "admin_handle" field.
func (_u *AdminReplyTimeUpdateOne) SetAdminHandle(v string) *AdminReplyTimeUpdateOne {
	_u.mutation.SetAdminHandle(v)
	return _u
}

// SetNillableAdminHandle sets the "admin_handle" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableAdminHandle(v *string) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetAdminHandle(*v)
	}
	return _u
}

// SetTimeDifferenceSeconds sets the "time_difference_seconds" field.
func (_u *AdminReplyTimeUpdateOne) SetTimeDifferenceSeconds(v int64) *AdminReplyTimeUpdateOne {
	_u.mutation.ResetTimeDifferenceSeconds()
	_u.mutation.SetTimeDifferenceSeconds(v)
	return _u
}

// SetNillableTimeDifferenceSeconds sets the "time_difference_seconds" field if the given value is not nil.
func (_u *AdminReplyTimeUpdateOne) SetNillableTimeDifferenceSeconds(v *int64) *AdminReplyTimeUpdateOne {
	if v != nil {
		_u.SetTimeDifferenceSeconds(*v)
	}
	return _u
}

// AddTimeDifferenceSeconds adds value to the "time_difference_seconds" field.
func (_u *AdminReplyTimeUpdateOne) AddTimeDifferenceSeconds(v int64) *AdminReplyTimeUpdateOne {
	_u.mutation.AddTimeDifferenceSeconds(v)
	return _u
}

// SetUserPost sets the "user_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdateOne) SetUserPost(v *Post) *AdminReplyTimeUpdateOne {
	return _u.SetUserPostID(v.ID)
}

// SetAdminPost sets the "admin_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdateOne) SetAdminPost(v *Post) *AdminReplyTimeUpdateOne {
	return _u.SetAdminPostID(v.ID)
}

// SetAdminAccount sets the "admin_account" edge to the Account entity.
func (_u *AdminReplyTimeUpdateOne) SetAdminAccount(v *Account) *AdminReplyTimeUpdateOne {
	return _u.SetAdminAccountID(v.ID)
}

// Mutation returns the AdminReplyTimeMutation object of the builder.
func (_u *AdminReplyTimeUpdateOne) Mutation() *AdminReplyTimeMutation {
	return _u.mutation
}

// ClearUserPost clears the "user_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdateOne) ClearUserPost() *AdminReplyTimeUpdateOne {
	_u.mutation.ClearUserPost()
	return _u
}

// ClearAdminPost clears the "admin_post" edge to the Post entity.
func (_u *AdminReplyTimeUpdateOne) ClearAdminPost() *AdminReplyTimeUpdateOne {
	_u.mutation.ClearAdminPost()
	return _u
}

// ClearAdminAccount clears the "admin_account" edge to the Account entity.
func (_u *AdminReplyTimeUpdateOne) ClearAdminAccount() *AdminReplyTimeUpdateOne {
	_u.mutation.ClearAdminAccount()
	return _u
}

// Where appends a list predicates to the AdminReplyTimeUpdate builder.
func (_u *AdminReplyTimeUpdateOne) Where(ps ...predicate.AdminReplyTime) *AdminReplyTimeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminReplyTimeUpdateOne) Select(field string, fields ...string) *AdminReplyTimeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminReplyTime entity.
func (_u *AdminReplyTimeUpdateOne) Save(ctx context.Context) (*AdminReplyTime, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminReplyTimeUpdateOne) SaveX(ctx context.Context) *AdminReplyTime {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminReplyTimeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminReplyTimeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminReplyTimeUpdateOne) check() error {
	if _u.mutation.UserPostCleared() && len(_u.mutation.UserPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminReplyTime.user_post"`)
	}
	if _u.mutation.AdminPostCleared() && len(_u.mutation.AdminPostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminReplyTime.admin_post"`)
	}
	if _u.mutation.AdminAccountCleared() && len(_u.mutation.AdminAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AdminReplyTime.admin_account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AdminReplyTimeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AdminReplyTimeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AdminReplyTimeUpdateOne) sqlSave(ctx context.Context) (_node *AdminReplyTime, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminreplytime.Table, adminreplytime.Columns, sqlgraph.NewFieldSpec(adminreplytime.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminReplyTime.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminreplytime.FieldID)
		for _, f := range fields {
			if !adminreplytime.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminreplytime.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserPostTime(); ok {
		_spec.SetField(adminreplytime.FieldUserPostTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AdminPostTime(); ok {
		_spec.SetField(adminreplytime.FieldAdminPostTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AdminHandle(); ok {
		_spec.SetField(adminreplytime.FieldAdminHandle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TimeDifferenceSeconds(); ok {
		_spec.SetField(adminreplytime.FieldTimeDifferenceSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeDifferenceSeconds(); ok {
		_spec.AddField(adminreplytime.FieldTimeDifferenceSeconds, field.TypeInt64, value)
	}
	if _u.mutation.UserPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.UserPostTable,
			Columns: []string{adminreplytime.UserPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.UserPostTable,
			Columns: []string{adminreplytime.UserPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminPostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminPostTable,
			Columns: []string{adminreplytime.AdminPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminPostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminPostTable,
			Columns: []string{adminreplytime.AdminPostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AdminAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminAccountTable,
			Columns: []string{adminreplytime.AdminAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AdminAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   adminreplytime.AdminAccountTable,
			Columns: []string{adminreplytime.AdminAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AdminReplyTime{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminreplytime.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
