// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/adminreplytime"
	"github.com/Southclaws/storyden/internal/ent/predicate"
)

// AdminReplyTimeDelete is the builder for deleting a AdminReplyTime entity.
type AdminReplyTimeDelete struct {
	config
	hooks    []Hook
	mutation *AdminReplyTimeMutation
}

// Where appends a list predicates to the AdminReplyTimeDelete builder.
func (_d *AdminReplyTimeDelete) Where(ps ...predicate.AdminReplyTime) *AdminReplyTimeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminReplyTimeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminReplyTimeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminReplyTimeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adminreplytime.Table, sqlgraph.NewFieldSpec(adminreplytime.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminReplyTimeDeleteOne is the builder for deleting a single AdminReplyTime entity.
type AdminReplyTimeDeleteOne struct {
	_d *AdminReplyTimeDelete
}

// Where appends a list predicates to the AdminReplyTimeDelete builder.
func (_d *AdminReplyTimeDeleteOne) Where(ps ...predicate.AdminReplyTime) *AdminReplyTimeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminReplyTimeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminreplytime.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminReplyTimeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
