// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/channelmembership"
	"github.com/rs/xid"
)

// ChannelMembershipCreate is the builder for creating a ChannelMembership entity.
type ChannelMembershipCreate struct {
	config
	mutation *ChannelMembershipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelMembershipCreate) SetCreatedAt(v time.Time) *ChannelMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelMembershipCreate) SetNillableCreatedAt(v *time.Time) *ChannelMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelMembershipCreate) SetChannelID(v xid.ID) *ChannelMembershipCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ChannelMembershipCreate) SetAccountID(v xid.ID) *ChannelMembershipCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ChannelMembershipCreate) SetRole(v channelmembership.Role) *ChannelMembershipCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *ChannelMembershipCreate) SetNillableRole(v *channelmembership.Role) *ChannelMembershipCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChannelMembershipCreate) SetID(v xid.ID) *ChannelMembershipCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChannelMembershipCreate) SetNillableID(v *xid.ID) *ChannelMembershipCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelMembershipCreate) SetChannel(v *Channel) *ChannelMembershipCreate {
	return _c.SetChannelID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ChannelMembershipCreate) SetAccount(v *Account) *ChannelMembershipCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the ChannelMembershipMutation object of the builder.
func (_c *ChannelMembershipCreate) Mutation() *ChannelMembershipMutation {
	return _c.mutation
}

// Save creates the ChannelMembership in the database.
func (_c *ChannelMembershipCreate) Save(ctx context.Context) (*ChannelMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelMembershipCreate) SaveX(ctx context.Context) *ChannelMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelMembershipCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelmembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := channelmembership.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := channelmembership.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelMembershipCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelMembership.created_at"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelMembership.channel_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ChannelMembership.account_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ChannelMembership.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := channelmembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChannelMembership.role": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := channelmembership.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ChannelMembership.id": %w`, err)}
		}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelMembership.channel"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ChannelMembership.account"`)}
	}
	return nil
}

func (_c *ChannelMembershipCreate) sqlSave(ctx context.Context) (*ChannelMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelMembershipCreate) createSpec() (*ChannelMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelmembership.Table, sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelmembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(channelmembership.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.ChannelTable,
			Columns: []string{channelmembership.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.AccountTable,
			Columns: []string{channelmembership.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelMembership.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelMembershipCreate) OnConflict(opts ...sql.ConflictOption) *ChannelMembershipUpsertOne {
	_c.conflict = opts
	return &ChannelMembershipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelMembershipCreate) OnConflictColumns(columns ...string) *ChannelMembershipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelMembershipUpsertOne{
		create: _c,
	}
}

type (
	// ChannelMembershipUpsertOne is the builder for "upsert"-ing
	//  one ChannelMembership node.
	ChannelMembershipUpsertOne struct {
		create *ChannelMembershipCreate
	}

	// ChannelMembershipUpsert is the "OnConflict" setter.
	ChannelMembershipUpsert struct {
		*sql.UpdateSet
	}
)

// SetChannelID sets the "channel_id" field.
func (u *ChannelMembershipUpsert) SetChannelID(v xid.ID) *ChannelMembershipUpsert {
	u.Set(channelmembership.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ChannelMembershipUpsert) UpdateChannelID() *ChannelMembershipUpsert {
	u.SetExcluded(channelmembership.FieldChannelID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ChannelMembershipUpsert) SetAccountID(v xid.ID) *ChannelMembershipUpsert {
	u.Set(channelmembership.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ChannelMembershipUpsert) UpdateAccountID() *ChannelMembershipUpsert {
	u.SetExcluded(channelmembership.FieldAccountID)
	return u
}

// SetRole sets the "role" field.
func (u *ChannelMembershipUpsert) SetRole(v channelmembership.Role) *ChannelMembershipUpsert {
	u.Set(channelmembership.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ChannelMembershipUpsert) UpdateRole() *ChannelMembershipUpsert {
	u.SetExcluded(channelmembership.FieldRole)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ChannelMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(channelmembership.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChannelMembershipUpsertOne) UpdateNewValues() *ChannelMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(channelmembership.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelmembership.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelMembership.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelMembershipUpsertOne) Ignore() *ChannelMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelMembershipUpsertOne) DoNothing() *ChannelMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelMembershipCreate.OnConflict
// documentation for more info.
func (u *ChannelMembershipUpsertOne) Update(set func(*ChannelMembershipUpsert)) *ChannelMembershipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *ChannelMembershipUpsertOne) SetChannelID(v xid.ID) *ChannelMembershipUpsertOne {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ChannelMembershipUpsertOne) UpdateChannelID() *ChannelMembershipUpsertOne {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.UpdateChannelID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ChannelMembershipUpsertOne) SetAccountID(v xid.ID) *ChannelMembershipUpsertOne {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ChannelMembershipUpsertOne) UpdateAccountID() *ChannelMembershipUpsertOne {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.UpdateAccountID()
	})
}

// SetRole sets the "role" field.
func (u *ChannelMembershipUpsertOne) SetRole(v channelmembership.Role) *ChannelMembershipUpsertOne {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ChannelMembershipUpsertOne) UpdateRole() *ChannelMembershipUpsertOne {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *ChannelMembershipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelMembershipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelMembershipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelMembershipUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ChannelMembershipUpsertOne.ID is not supported by MySQL driver. Use ChannelMembershipUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelMembershipUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelMembershipCreateBulk is the builder for creating many ChannelMembership entities in bulk.
type ChannelMembershipCreateBulk struct {
	config
	err      error
	builders []*ChannelMembershipCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelMembership entities in the database.
func (_c *ChannelMembershipCreateBulk) Save(ctx context.Context) ([]*ChannelMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelMembershipCreateBulk) SaveX(ctx context.Context) []*ChannelMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelMembership.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelMembershipUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelMembershipCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelMembershipUpsertBulk {
	_c.conflict = opts
	return &ChannelMembershipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelMembership.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelMembershipCreateBulk) OnConflictColumns(columns ...string) *ChannelMembershipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelMembershipUpsertBulk{
		create: _c,
	}
}

// ChannelMembershipUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelMembership nodes.
type ChannelMembershipUpsertBulk struct {
	create *ChannelMembershipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelMembership.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(channelmembership.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChannelMembershipUpsertBulk) UpdateNewValues() *ChannelMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(channelmembership.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelmembership.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelMembership.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelMembershipUpsertBulk) Ignore() *ChannelMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelMembershipUpsertBulk) DoNothing() *ChannelMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelMembershipCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelMembershipUpsertBulk) Update(set func(*ChannelMembershipUpsert)) *ChannelMembershipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelMembershipUpsert{UpdateSet: update})
	}))
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *ChannelMembershipUpsertBulk) SetChannelID(v xid.ID) *ChannelMembershipUpsertBulk {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ChannelMembershipUpsertBulk) UpdateChannelID() *ChannelMembershipUpsertBulk {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.UpdateChannelID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ChannelMembershipUpsertBulk) SetAccountID(v xid.ID) *ChannelMembershipUpsertBulk {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ChannelMembershipUpsertBulk) UpdateAccountID() *ChannelMembershipUpsertBulk {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.UpdateAccountID()
	})
}

// SetRole sets the "role" field.
func (u *ChannelMembershipUpsertBulk) SetRole(v channelmembership.Role) *ChannelMembershipUpsertBulk {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ChannelMembershipUpsertBulk) UpdateRole() *ChannelMembershipUpsertBulk {
	return u.Update(func(s *ChannelMembershipUpsert) {
		s.UpdateRole()
	})
}

// Exec executes the query.
func (u *ChannelMembershipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelMembershipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelMembershipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelMembershipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
