// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/channelmembership"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// ChannelMembershipUpdate is the builder for updating ChannelMembership entities.
type ChannelMembershipUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelMembershipMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelMembershipUpdate builder.
func (_u *ChannelMembershipUpdate) Where(ps ...predicate.ChannelMembership) *ChannelMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ChannelMembershipUpdate) SetChannelID(v xid.ID) *ChannelMembershipUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ChannelMembershipUpdate) SetNillableChannelID(v *xid.ID) *ChannelMembershipUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ChannelMembershipUpdate) SetAccountID(v xid.ID) *ChannelMembershipUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ChannelMembershipUpdate) SetNillableAccountID(v *xid.ID) *ChannelMembershipUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ChannelMembershipUpdate) SetRole(v channelmembership.Role) *ChannelMembershipUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ChannelMembershipUpdate) SetNillableRole(v *channelmembership.Role) *ChannelMembershipUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelMembershipUpdate) SetChannel(v *Channel) *ChannelMembershipUpdate {
	return _u.SetChannelID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ChannelMembershipUpdate) SetAccount(v *Account) *ChannelMembershipUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ChannelMembershipMutation object of the builder.
func (_u *ChannelMembershipUpdate) Mutation() *ChannelMembershipMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelMembershipUpdate) ClearChannel() *ChannelMembershipUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ChannelMembershipUpdate) ClearAccount() *ChannelMembershipUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelMembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMembershipUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := channelmembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChannelMembership.role": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMembership.channel"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMembership.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelMembershipUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelMembershipUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmembership.Table, channelmembership.Columns, sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(channelmembership.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.ChannelTable,
			Columns: []string{channelmembership.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.ChannelTable,
			Columns: []string{channelmembership.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.AccountTable,
			Columns: []string{channelmembership.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.AccountTable,
			Columns: []string{channelmembership.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelMembershipUpdateOne is the builder for updating a single ChannelMembership entity.
type ChannelMembershipUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelMembershipMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChannelID sets the "channel_id" field.
func (_u *ChannelMembershipUpdateOne) SetChannelID(v xid.ID) *ChannelMembershipUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ChannelMembershipUpdateOne) SetNillableChannelID(v *xid.ID) *ChannelMembershipUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ChannelMembershipUpdateOne) SetAccountID(v xid.ID) *ChannelMembershipUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ChannelMembershipUpdateOne) SetNillableAccountID(v *xid.ID) *ChannelMembershipUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ChannelMembershipUpdateOne) SetRole(v channelmembership.Role) *ChannelMembershipUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ChannelMembershipUpdateOne) SetNillableRole(v *channelmembership.Role) *ChannelMembershipUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ChannelMembershipUpdateOne) SetChannel(v *Channel) *ChannelMembershipUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ChannelMembershipUpdateOne) SetAccount(v *Account) *ChannelMembershipUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ChannelMembershipMutation object of the builder.
func (_u *ChannelMembershipUpdateOne) Mutation() *ChannelMembershipMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ChannelMembershipUpdateOne) ClearChannel() *ChannelMembershipUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ChannelMembershipUpdateOne) ClearAccount() *ChannelMembershipUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ChannelMembershipUpdate builder.
func (_u *ChannelMembershipUpdateOne) Where(ps ...predicate.ChannelMembership) *ChannelMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelMembershipUpdateOne) Select(field string, fields ...string) *ChannelMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelMembership entity.
func (_u *ChannelMembershipUpdateOne) Save(ctx context.Context) (*ChannelMembership, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelMembershipUpdateOne) SaveX(ctx context.Context) *ChannelMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := channelmembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChannelMembership.role": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMembership.channel"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelMembership.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelMembershipUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelMembershipUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelMembershipUpdateOne) sqlSave(ctx context.Context) (_node *ChannelMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelmembership.Table, channelmembership.Columns, sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelmembership.FieldID)
		for _, f := range fields {
			if !channelmembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelmembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(channelmembership.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.ChannelTable,
			Columns: []string{channelmembership.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.ChannelTable,
			Columns: []string{channelmembership.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.AccountTable,
			Columns: []string{channelmembership.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channelmembership.AccountTable,
			Columns: []string{channelmembership.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChannelMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelmembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
