// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/channelmembership"
	"github.com/rs/xid"
)

// ChannelMembership is the model entity for the ChannelMembership schema.
type ChannelMembership struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The channel this membership belongs to
	ChannelID xid.ID `json:"channel_id,omitempty"`
	// The account that is a member of the channel
	AccountID xid.ID `json:"account_id,omitempty"`
	// The role of the member in the channel: owner > admin > moderator > member
	Role channelmembership.Role `json:"role,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelMembershipQuery when eager-loading is set.
	Edges               ChannelMembershipEdges `json:"edges"`
	channel_memberships *xid.ID
	selectValues        sql.SelectValues
}

// ChannelMembershipEdges holds the relations/edges for other nodes in the graph.
type ChannelMembershipEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelMembershipEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelMembershipEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelmembership.FieldRole:
			values[i] = new(sql.NullString)
		case channelmembership.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case channelmembership.FieldID, channelmembership.FieldChannelID, channelmembership.FieldAccountID:
			values[i] = new(xid.ID)
		case channelmembership.ForeignKeys[0]: // channel_memberships
			values[i] = &sql.NullScanner{S: new(xid.ID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelMembership fields.
func (_m *ChannelMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelmembership.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case channelmembership.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelmembership.FieldChannelID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value != nil {
				_m.ChannelID = *value
			}
		case channelmembership.FieldAccountID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value != nil {
				_m.AccountID = *value
			}
		case channelmembership.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = channelmembership.Role(value.String)
			}
		case channelmembership.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field channel_memberships", values[i])
			} else if value.Valid {
				_m.channel_memberships = new(xid.ID)
				*_m.channel_memberships = *value.S.(*xid.ID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelMembership.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelMembership) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelMembership entity.
func (_m *ChannelMembership) QueryChannel() *ChannelQuery {
	return NewChannelMembershipClient(_m.config).QueryChannel(_m)
}

// QueryAccount queries the "account" edge of the ChannelMembership entity.
func (_m *ChannelMembership) QueryAccount() *AccountQuery {
	return NewChannelMembershipClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this ChannelMembership.
// Note that you need to call ChannelMembership.Unwrap() before calling this method if this ChannelMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelMembership) Update() *ChannelMembershipUpdateOne {
	return NewChannelMembershipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelMembership) Unwrap() *ChannelMembership {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelMembership is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelMembership) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelMembership(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelMemberships is a parsable slice of ChannelMembership.
type ChannelMemberships []*ChannelMembership
