// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/channelmembership"
	"github.com/Southclaws/storyden/internal/ent/predicate"
)

// ChannelMembershipDelete is the builder for deleting a ChannelMembership entity.
type ChannelMembershipDelete struct {
	config
	hooks    []Hook
	mutation *ChannelMembershipMutation
}

// Where appends a list predicates to the ChannelMembershipDelete builder.
func (_d *ChannelMembershipDelete) Where(ps ...predicate.ChannelMembership) *ChannelMembershipDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelMembershipDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelMembershipDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelMembershipDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelmembership.Table, sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelMembershipDeleteOne is the builder for deleting a single ChannelMembership entity.
type ChannelMembershipDeleteOne struct {
	_d *ChannelMembershipDelete
}

// Where appends a list predicates to the ChannelMembershipDelete builder.
func (_d *ChannelMembershipDeleteOne) Where(ps ...predicate.ChannelMembership) *ChannelMembershipDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelMembershipDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelmembership.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelMembershipDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
