// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/asset"
	"github.com/Southclaws/storyden/internal/ent/category"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/channelmembership"
	"github.com/Southclaws/storyden/internal/ent/collection"
	"github.com/Southclaws/storyden/internal/ent/node"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// ChannelQuery is the builder for querying Channel entities.
type ChannelQuery struct {
	config
	ctx             *QueryContext
	order           []channel.OrderOption
	inters          []Interceptor
	predicates      []predicate.Channel
	withCoverImage  *AssetQuery
	withIcon        *AssetQuery
	withMemberships *ChannelMembershipQuery
	withCategories  *CategoryQuery
	withCollections *CollectionQuery
	withPosts       *PostQuery
	withNodes       *NodeQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChannelQuery builder.
func (_q *ChannelQuery) Where(ps ...predicate.Channel) *ChannelQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChannelQuery) Limit(limit int) *ChannelQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChannelQuery) Offset(offset int) *ChannelQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChannelQuery) Unique(unique bool) *ChannelQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChannelQuery) Order(o ...channel.OrderOption) *ChannelQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCoverImage chains the current query on the "cover_image" edge.
func (_q *ChannelQuery) QueryCoverImage() *AssetQuery {
	query := (&AssetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, channel.CoverImageTable, channel.CoverImageColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIcon chains the current query on the "icon" edge.
func (_q *ChannelQuery) QueryIcon() *AssetQuery {
	query := (&AssetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(asset.Table, asset.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, channel.IconTable, channel.IconColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMemberships chains the current query on the "memberships" edge.
func (_q *ChannelQuery) QueryMemberships() *ChannelMembershipQuery {
	query := (&ChannelMembershipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(channelmembership.Table, channelmembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.MembershipsTable, channel.MembershipsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategories chains the current query on the "categories" edge.
func (_q *ChannelQuery) QueryCategories() *CategoryQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.CategoriesTable, channel.CategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCollections chains the current query on the "collections" edge.
func (_q *ChannelQuery) QueryCollections() *CollectionQuery {
	query := (&CollectionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(collection.Table, collection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.CollectionsTable, channel.CollectionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPosts chains the current query on the "posts" edge.
func (_q *ChannelQuery) QueryPosts() *PostQuery {
	query := (&PostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.PostsTable, channel.PostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNodes chains the current query on the "nodes" edge.
func (_q *ChannelQuery) QueryNodes() *NodeQuery {
	query := (&NodeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(channel.Table, channel.FieldID, selector),
			sqlgraph.To(node.Table, node.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, channel.NodesTable, channel.NodesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Channel entity from the query.
// Returns a *NotFoundError when no Channel was found.
func (_q *ChannelQuery) First(ctx context.Context) (*Channel, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{channel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChannelQuery) FirstX(ctx context.Context) *Channel {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Channel ID from the query.
// Returns a *NotFoundError when no Channel ID was found.
func (_q *ChannelQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{channel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChannelQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Channel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Channel entity is found.
// Returns a *NotFoundError when no Channel entities are found.
func (_q *ChannelQuery) Only(ctx context.Context) (*Channel, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{channel.Label}
	default:
		return nil, &NotSingularError{channel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChannelQuery) OnlyX(ctx context.Context) *Channel {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Channel ID in the query.
// Returns a *NotSingularError when more than one Channel ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChannelQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{channel.Label}
	default:
		err = &NotSingularError{channel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChannelQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Channels.
func (_q *ChannelQuery) All(ctx context.Context) ([]*Channel, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Channel, *ChannelQuery]()
	return withInterceptors[[]*Channel](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChannelQuery) AllX(ctx context.Context) []*Channel {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Channel IDs.
func (_q *ChannelQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(channel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChannelQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChannelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChannelQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChannelQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChannelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChannelQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChannelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChannelQuery) Clone() *ChannelQuery {
	if _q == nil {
		return nil
	}
	return &ChannelQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]channel.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.Channel{}, _q.predicates...),
		withCoverImage:  _q.withCoverImage.Clone(),
		withIcon:        _q.withIcon.Clone(),
		withMemberships: _q.withMemberships.Clone(),
		withCategories:  _q.withCategories.Clone(),
		withCollections: _q.withCollections.Clone(),
		withPosts:       _q.withPosts.Clone(),
		withNodes:       _q.withNodes.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithCoverImage tells the query-builder to eager-load the nodes that are connected to
// the "cover_image" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithCoverImage(opts ...func(*AssetQuery)) *ChannelQuery {
	query := (&AssetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCoverImage = query
	return _q
}

// WithIcon tells the query-builder to eager-load the nodes that are connected to
// the "icon" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithIcon(opts ...func(*AssetQuery)) *ChannelQuery {
	query := (&AssetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIcon = query
	return _q
}

// WithMemberships tells the query-builder to eager-load the nodes that are connected to
// the "memberships" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithMemberships(opts ...func(*ChannelMembershipQuery)) *ChannelQuery {
	query := (&ChannelMembershipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMemberships = query
	return _q
}

// WithCategories tells the query-builder to eager-load the nodes that are connected to
// the "categories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithCategories(opts ...func(*CategoryQuery)) *ChannelQuery {
	query := (&CategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCategories = query
	return _q
}

// WithCollections tells the query-builder to eager-load the nodes that are connected to
// the "collections" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithCollections(opts ...func(*CollectionQuery)) *ChannelQuery {
	query := (&CollectionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCollections = query
	return _q
}

// WithPosts tells the query-builder to eager-load the nodes that are connected to
// the "posts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithPosts(opts ...func(*PostQuery)) *ChannelQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPosts = query
	return _q
}

// WithNodes tells the query-builder to eager-load the nodes that are connected to
// the "nodes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChannelQuery) WithNodes(opts ...func(*NodeQuery)) *ChannelQuery {
	query := (&NodeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNodes = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Channel.Query().
//		GroupBy(channel.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChannelQuery) GroupBy(field string, fields ...string) *ChannelGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChannelGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = channel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Channel.Query().
//		Select(channel.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ChannelQuery) Select(fields ...string) *ChannelSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChannelSelect{ChannelQuery: _q}
	sbuild.label = channel.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChannelSelect configured with the given aggregations.
func (_q *ChannelQuery) Aggregate(fns ...AggregateFunc) *ChannelSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChannelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !channel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChannelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Channel, error) {
	var (
		nodes       = []*Channel{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withCoverImage != nil,
			_q.withIcon != nil,
			_q.withMemberships != nil,
			_q.withCategories != nil,
			_q.withCollections != nil,
			_q.withPosts != nil,
			_q.withNodes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Channel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Channel{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCoverImage; query != nil {
		if err := _q.loadCoverImage(ctx, query, nodes, nil,
			func(n *Channel, e *Asset) { n.Edges.CoverImage = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIcon; query != nil {
		if err := _q.loadIcon(ctx, query, nodes, nil,
			func(n *Channel, e *Asset) { n.Edges.Icon = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMemberships; query != nil {
		if err := _q.loadMemberships(ctx, query, nodes,
			func(n *Channel) { n.Edges.Memberships = []*ChannelMembership{} },
			func(n *Channel, e *ChannelMembership) { n.Edges.Memberships = append(n.Edges.Memberships, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCategories; query != nil {
		if err := _q.loadCategories(ctx, query, nodes,
			func(n *Channel) { n.Edges.Categories = []*Category{} },
			func(n *Channel, e *Category) { n.Edges.Categories = append(n.Edges.Categories, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCollections; query != nil {
		if err := _q.loadCollections(ctx, query, nodes,
			func(n *Channel) { n.Edges.Collections = []*Collection{} },
			func(n *Channel, e *Collection) { n.Edges.Collections = append(n.Edges.Collections, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPosts; query != nil {
		if err := _q.loadPosts(ctx, query, nodes,
			func(n *Channel) { n.Edges.Posts = []*Post{} },
			func(n *Channel, e *Post) { n.Edges.Posts = append(n.Edges.Posts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNodes; query != nil {
		if err := _q.loadNodes(ctx, query, nodes,
			func(n *Channel) { n.Edges.Nodes = []*Node{} },
			func(n *Channel, e *Node) { n.Edges.Nodes = append(n.Edges.Nodes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChannelQuery) loadCoverImage(ctx context.Context, query *AssetQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *Asset)) error {
	ids := make([]xid.ID, 0, len(nodes))
	nodeids := make(map[xid.ID][]*Channel)
	for i := range nodes {
		if nodes[i].CoverImageAssetID == nil {
			continue
		}
		fk := *nodes[i].CoverImageAssetID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(asset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cover_image_asset_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChannelQuery) loadIcon(ctx context.Context, query *AssetQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *Asset)) error {
	ids := make([]xid.ID, 0, len(nodes))
	nodeids := make(map[xid.ID][]*Channel)
	for i := range nodes {
		if nodes[i].IconAssetID == nil {
			continue
		}
		fk := *nodes[i].IconAssetID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(asset.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "icon_asset_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChannelQuery) loadMemberships(ctx context.Context, query *ChannelMembershipQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *ChannelMembership)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.ChannelMembership(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.MembershipsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.channel_memberships
		if fk == nil {
			return fmt.Errorf(`foreign-key "channel_memberships" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_memberships" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChannelQuery) loadCategories(ctx context.Context, query *CategoryQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *Category)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(category.FieldChannelID)
	}
	query.Where(predicate.Category(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.CategoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChannelID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChannelQuery) loadCollections(ctx context.Context, query *CollectionQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *Collection)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(collection.FieldChannelID)
	}
	query.Where(predicate.Collection(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.CollectionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChannelID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChannelQuery) loadPosts(ctx context.Context, query *PostQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *Post)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(post.FieldChannelID)
	}
	query.Where(predicate.Post(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.PostsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChannelID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChannelQuery) loadNodes(ctx context.Context, query *NodeQuery, nodes []*Channel, init func(*Channel), assign func(*Channel, *Node)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[xid.ID]*Channel)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(node.FieldChannelID)
	}
	query.Where(predicate.Node(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(channel.NodesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChannelID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "channel_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChannelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChannelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for i := range fields {
			if fields[i] != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCoverImage != nil {
			_spec.Node.AddColumnOnce(channel.FieldCoverImageAssetID)
		}
		if _q.withIcon != nil {
			_spec.Node.AddColumnOnce(channel.FieldIconAssetID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChannelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(channel.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = channel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *ChannelQuery) Modify(modifiers ...func(s *sql.Selector)) *ChannelSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// ChannelGroupBy is the group-by builder for Channel entities.
type ChannelGroupBy struct {
	selector
	build *ChannelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChannelGroupBy) Aggregate(fns ...AggregateFunc) *ChannelGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChannelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelQuery, *ChannelGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChannelGroupBy) sqlScan(ctx context.Context, root *ChannelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChannelSelect is the builder for selecting fields of Channel entities.
type ChannelSelect struct {
	*ChannelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChannelSelect) Aggregate(fns ...AggregateFunc) *ChannelSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChannelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChannelQuery, *ChannelSelect](ctx, _s.ChannelQuery, _s, _s.inters, v)
}

func (_s *ChannelSelect) sqlScan(ctx context.Context, root *ChannelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *ChannelSelect) Modify(modifiers ...func(s *sql.Selector)) *ChannelSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
