// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/asset"
	"github.com/Southclaws/storyden/internal/ent/category"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/channelmembership"
	"github.com/Southclaws/storyden/internal/ent/collection"
	"github.com/Southclaws/storyden/internal/ent/node"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUpdate) SetUpdatedAt(v time.Time) *ChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdate) SetName(v string) *ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ChannelUpdate) SetSlug(v string) *ChannelUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableSlug(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ChannelUpdate) SetDescription(v string) *ChannelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableDescription(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ChannelUpdate) ClearDescription() *ChannelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCoverImageAssetID sets the "cover_image_asset_id" field.
func (_u *ChannelUpdate) SetCoverImageAssetID(v xid.ID) *ChannelUpdate {
	_u.mutation.SetCoverImageAssetID(v)
	return _u
}

// SetNillableCoverImageAssetID sets the "cover_image_asset_id" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableCoverImageAssetID(v *xid.ID) *ChannelUpdate {
	if v != nil {
		_u.SetCoverImageAssetID(*v)
	}
	return _u
}

// ClearCoverImageAssetID clears the value of the "cover_image_asset_id" field.
func (_u *ChannelUpdate) ClearCoverImageAssetID() *ChannelUpdate {
	_u.mutation.ClearCoverImageAssetID()
	return _u
}

// SetIconAssetID sets the "icon_asset_id" field.
func (_u *ChannelUpdate) SetIconAssetID(v xid.ID) *ChannelUpdate {
	_u.mutation.SetIconAssetID(v)
	return _u
}

// SetNillableIconAssetID sets the "icon_asset_id" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableIconAssetID(v *xid.ID) *ChannelUpdate {
	if v != nil {
		_u.SetIconAssetID(*v)
	}
	return _u
}

// ClearIconAssetID clears the value of the "icon_asset_id" field.
func (_u *ChannelUpdate) ClearIconAssetID() *ChannelUpdate {
	_u.mutation.ClearIconAssetID()
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ChannelUpdate) SetVisibility(v channel.Visibility) *ChannelUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableVisibility(v *channel.Visibility) *ChannelUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChannelUpdate) SetMetadata(v map[string]interface{}) *ChannelUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChannelUpdate) ClearMetadata() *ChannelUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCoverImageID sets the "cover_image" edge to the Asset entity by ID.
func (_u *ChannelUpdate) SetCoverImageID(id xid.ID) *ChannelUpdate {
	_u.mutation.SetCoverImageID(id)
	return _u
}

// SetNillableCoverImageID sets the "cover_image" edge to the Asset entity by ID if the given value is not nil.
func (_u *ChannelUpdate) SetNillableCoverImageID(id *xid.ID) *ChannelUpdate {
	if id != nil {
		_u = _u.SetCoverImageID(*id)
	}
	return _u
}

// SetCoverImage sets the "cover_image" edge to the Asset entity.
func (_u *ChannelUpdate) SetCoverImage(v *Asset) *ChannelUpdate {
	return _u.SetCoverImageID(v.ID)
}

// SetIconID sets the "icon" edge to the Asset entity by ID.
func (_u *ChannelUpdate) SetIconID(id xid.ID) *ChannelUpdate {
	_u.mutation.SetIconID(id)
	return _u
}

// SetNillableIconID sets the "icon" edge to the Asset entity by ID if the given value is not nil.
func (_u *ChannelUpdate) SetNillableIconID(id *xid.ID) *ChannelUpdate {
	if id != nil {
		_u = _u.SetIconID(*id)
	}
	return _u
}

// SetIcon sets the "icon" edge to the Asset entity.
func (_u *ChannelUpdate) SetIcon(v *Asset) *ChannelUpdate {
	return _u.SetIconID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the ChannelMembership entity by IDs.
func (_u *ChannelUpdate) AddMembershipIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the ChannelMembership entity.
func (_u *ChannelUpdate) AddMemberships(v ...*ChannelMembership) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_u *ChannelUpdate) AddCategoryIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.AddCategoryIDs(ids...)
	return _u
}

// AddCategories adds the "categories" edges to the Category entity.
func (_u *ChannelUpdate) AddCategories(v ...*Category) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryIDs(ids...)
}

// AddCollectionIDs adds the "collections" edge to the Collection entity by IDs.
func (_u *ChannelUpdate) AddCollectionIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.AddCollectionIDs(ids...)
	return _u
}

// AddCollections adds the "collections" edges to the Collection entity.
func (_u *ChannelUpdate) AddCollections(v ...*Collection) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionIDs(ids...)
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *ChannelUpdate) AddPostIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *ChannelUpdate) AddPosts(v ...*Post) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *ChannelUpdate) AddNodeIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *ChannelUpdate) AddNodes(v ...*Node) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdate) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearCoverImage clears the "cover_image" edge to the Asset entity.
func (_u *ChannelUpdate) ClearCoverImage() *ChannelUpdate {
	_u.mutation.ClearCoverImage()
	return _u
}

// ClearIcon clears the "icon" edge to the Asset entity.
func (_u *ChannelUpdate) ClearIcon() *ChannelUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// ClearMemberships clears all "memberships" edges to the ChannelMembership entity.
func (_u *ChannelUpdate) ClearMemberships() *ChannelUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to ChannelMembership entities by IDs.
func (_u *ChannelUpdate) RemoveMembershipIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to ChannelMembership entities.
func (_u *ChannelUpdate) RemoveMemberships(v ...*ChannelMembership) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearCategories clears all "categories" edges to the Category entity.
func (_u *ChannelUpdate) ClearCategories() *ChannelUpdate {
	_u.mutation.ClearCategories()
	return _u
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (_u *ChannelUpdate) RemoveCategoryIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.RemoveCategoryIDs(ids...)
	return _u
}

// RemoveCategories removes "categories" edges to Category entities.
func (_u *ChannelUpdate) RemoveCategories(v ...*Category) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryIDs(ids...)
}

// ClearCollections clears all "collections" edges to the Collection entity.
func (_u *ChannelUpdate) ClearCollections() *ChannelUpdate {
	_u.mutation.ClearCollections()
	return _u
}

// RemoveCollectionIDs removes the "collections" edge to Collection entities by IDs.
func (_u *ChannelUpdate) RemoveCollectionIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.RemoveCollectionIDs(ids...)
	return _u
}

// RemoveCollections removes "collections" edges to Collection entities.
func (_u *ChannelUpdate) RemoveCollections(v ...*Collection) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionIDs(ids...)
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *ChannelUpdate) ClearPosts() *ChannelUpdate {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *ChannelUpdate) RemovePostIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *ChannelUpdate) RemovePosts(v ...*Post) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *ChannelUpdate) ClearNodes() *ChannelUpdate {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *ChannelUpdate) RemoveNodeIDs(ids ...xid.ID) *ChannelUpdate {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *ChannelUpdate) RemoveNodes(v ...*Node) *ChannelUpdate {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdate) check() error {
	if v, ok := _u.mutation.Visibility(); ok {
		if err := channel.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Channel.visibility": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(channel.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(channel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(channel.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(channel.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(channel.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(channel.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.CoverImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.CoverImageTable,
			Columns: []string{channel.CoverImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoverImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.CoverImageTable,
			Columns: []string{channel.CoverImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IconCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.IconTable,
			Columns: []string{channel.IconColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IconIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.IconTable,
			Columns: []string{channel.IconColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MembershipsTable,
			Columns: []string{channel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MembershipsTable,
			Columns: []string{channel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MembershipsTable,
			Columns: []string{channel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CategoriesTable,
			Columns: []string{channel.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !_u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CategoriesTable,
			Columns: []string{channel.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CategoriesTable,
			Columns: []string{channel.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CollectionsTable,
			Columns: []string{channel.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionsIDs(); len(nodes) > 0 && !_u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CollectionsTable,
			Columns: []string{channel.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CollectionsTable,
			Columns: []string{channel.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PostsTable,
			Columns: []string{channel.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PostsTable,
			Columns: []string{channel.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PostsTable,
			Columns: []string{channel.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.NodesTable,
			Columns: []string{channel.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.NodesTable,
			Columns: []string{channel.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.NodesTable,
			Columns: []string{channel.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelUpdateOne) SetUpdatedAt(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdateOne) SetName(v string) *ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ChannelUpdateOne) SetSlug(v string) *ChannelUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableSlug(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ChannelUpdateOne) SetDescription(v string) *ChannelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableDescription(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ChannelUpdateOne) ClearDescription() *ChannelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCoverImageAssetID sets the "cover_image_asset_id" field.
func (_u *ChannelUpdateOne) SetCoverImageAssetID(v xid.ID) *ChannelUpdateOne {
	_u.mutation.SetCoverImageAssetID(v)
	return _u
}

// SetNillableCoverImageAssetID sets the "cover_image_asset_id" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableCoverImageAssetID(v *xid.ID) *ChannelUpdateOne {
	if v != nil {
		_u.SetCoverImageAssetID(*v)
	}
	return _u
}

// ClearCoverImageAssetID clears the value of the "cover_image_asset_id" field.
func (_u *ChannelUpdateOne) ClearCoverImageAssetID() *ChannelUpdateOne {
	_u.mutation.ClearCoverImageAssetID()
	return _u
}

// SetIconAssetID sets the "icon_asset_id" field.
func (_u *ChannelUpdateOne) SetIconAssetID(v xid.ID) *ChannelUpdateOne {
	_u.mutation.SetIconAssetID(v)
	return _u
}

// SetNillableIconAssetID sets the "icon_asset_id" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableIconAssetID(v *xid.ID) *ChannelUpdateOne {
	if v != nil {
		_u.SetIconAssetID(*v)
	}
	return _u
}

// ClearIconAssetID clears the value of the "icon_asset_id" field.
func (_u *ChannelUpdateOne) ClearIconAssetID() *ChannelUpdateOne {
	_u.mutation.ClearIconAssetID()
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ChannelUpdateOne) SetVisibility(v channel.Visibility) *ChannelUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableVisibility(v *channel.Visibility) *ChannelUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChannelUpdateOne) SetMetadata(v map[string]interface{}) *ChannelUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChannelUpdateOne) ClearMetadata() *ChannelUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCoverImageID sets the "cover_image" edge to the Asset entity by ID.
func (_u *ChannelUpdateOne) SetCoverImageID(id xid.ID) *ChannelUpdateOne {
	_u.mutation.SetCoverImageID(id)
	return _u
}

// SetNillableCoverImageID sets the "cover_image" edge to the Asset entity by ID if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableCoverImageID(id *xid.ID) *ChannelUpdateOne {
	if id != nil {
		_u = _u.SetCoverImageID(*id)
	}
	return _u
}

// SetCoverImage sets the "cover_image" edge to the Asset entity.
func (_u *ChannelUpdateOne) SetCoverImage(v *Asset) *ChannelUpdateOne {
	return _u.SetCoverImageID(v.ID)
}

// SetIconID sets the "icon" edge to the Asset entity by ID.
func (_u *ChannelUpdateOne) SetIconID(id xid.ID) *ChannelUpdateOne {
	_u.mutation.SetIconID(id)
	return _u
}

// SetNillableIconID sets the "icon" edge to the Asset entity by ID if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableIconID(id *xid.ID) *ChannelUpdateOne {
	if id != nil {
		_u = _u.SetIconID(*id)
	}
	return _u
}

// SetIcon sets the "icon" edge to the Asset entity.
func (_u *ChannelUpdateOne) SetIcon(v *Asset) *ChannelUpdateOne {
	return _u.SetIconID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the ChannelMembership entity by IDs.
func (_u *ChannelUpdateOne) AddMembershipIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the ChannelMembership entity.
func (_u *ChannelUpdateOne) AddMemberships(v ...*ChannelMembership) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_u *ChannelUpdateOne) AddCategoryIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.AddCategoryIDs(ids...)
	return _u
}

// AddCategories adds the "categories" edges to the Category entity.
func (_u *ChannelUpdateOne) AddCategories(v ...*Category) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryIDs(ids...)
}

// AddCollectionIDs adds the "collections" edge to the Collection entity by IDs.
func (_u *ChannelUpdateOne) AddCollectionIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.AddCollectionIDs(ids...)
	return _u
}

// AddCollections adds the "collections" edges to the Collection entity.
func (_u *ChannelUpdateOne) AddCollections(v ...*Collection) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionIDs(ids...)
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (_u *ChannelUpdateOne) AddPostIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.AddPostIDs(ids...)
	return _u
}

// AddPosts adds the "posts" edges to the Post entity.
func (_u *ChannelUpdateOne) AddPosts(v ...*Post) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPostIDs(ids...)
}

// AddNodeIDs adds the "nodes" edge to the Node entity by IDs.
func (_u *ChannelUpdateOne) AddNodeIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.AddNodeIDs(ids...)
	return _u
}

// AddNodes adds the "nodes" edges to the Node entity.
func (_u *ChannelUpdateOne) AddNodes(v ...*Node) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNodeIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdateOne) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearCoverImage clears the "cover_image" edge to the Asset entity.
func (_u *ChannelUpdateOne) ClearCoverImage() *ChannelUpdateOne {
	_u.mutation.ClearCoverImage()
	return _u
}

// ClearIcon clears the "icon" edge to the Asset entity.
func (_u *ChannelUpdateOne) ClearIcon() *ChannelUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// ClearMemberships clears all "memberships" edges to the ChannelMembership entity.
func (_u *ChannelUpdateOne) ClearMemberships() *ChannelUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to ChannelMembership entities by IDs.
func (_u *ChannelUpdateOne) RemoveMembershipIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to ChannelMembership entities.
func (_u *ChannelUpdateOne) RemoveMemberships(v ...*ChannelMembership) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearCategories clears all "categories" edges to the Category entity.
func (_u *ChannelUpdateOne) ClearCategories() *ChannelUpdateOne {
	_u.mutation.ClearCategories()
	return _u
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (_u *ChannelUpdateOne) RemoveCategoryIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.RemoveCategoryIDs(ids...)
	return _u
}

// RemoveCategories removes "categories" edges to Category entities.
func (_u *ChannelUpdateOne) RemoveCategories(v ...*Category) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryIDs(ids...)
}

// ClearCollections clears all "collections" edges to the Collection entity.
func (_u *ChannelUpdateOne) ClearCollections() *ChannelUpdateOne {
	_u.mutation.ClearCollections()
	return _u
}

// RemoveCollectionIDs removes the "collections" edge to Collection entities by IDs.
func (_u *ChannelUpdateOne) RemoveCollectionIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.RemoveCollectionIDs(ids...)
	return _u
}

// RemoveCollections removes "collections" edges to Collection entities.
func (_u *ChannelUpdateOne) RemoveCollections(v ...*Collection) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionIDs(ids...)
}

// ClearPosts clears all "posts" edges to the Post entity.
func (_u *ChannelUpdateOne) ClearPosts() *ChannelUpdateOne {
	_u.mutation.ClearPosts()
	return _u
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (_u *ChannelUpdateOne) RemovePostIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.RemovePostIDs(ids...)
	return _u
}

// RemovePosts removes "posts" edges to Post entities.
func (_u *ChannelUpdateOne) RemovePosts(v ...*Post) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePostIDs(ids...)
}

// ClearNodes clears all "nodes" edges to the Node entity.
func (_u *ChannelUpdateOne) ClearNodes() *ChannelUpdateOne {
	_u.mutation.ClearNodes()
	return _u
}

// RemoveNodeIDs removes the "nodes" edge to Node entities by IDs.
func (_u *ChannelUpdateOne) RemoveNodeIDs(ids ...xid.ID) *ChannelUpdateOne {
	_u.mutation.RemoveNodeIDs(ids...)
	return _u
}

// RemoveNodes removes "nodes" edges to Node entities.
func (_u *ChannelUpdateOne) RemoveNodes(v ...*Node) *ChannelUpdateOne {
	ids := make([]xid.ID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNodeIDs(ids...)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Channel entity.
func (_u *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Visibility(); ok {
		if err := channel.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Channel.visibility": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(channel.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(channel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(channel.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(channel.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(channel.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(channel.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.CoverImageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.CoverImageTable,
			Columns: []string{channel.CoverImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CoverImageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.CoverImageTable,
			Columns: []string{channel.CoverImageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IconCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.IconTable,
			Columns: []string{channel.IconColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IconIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   channel.IconTable,
			Columns: []string{channel.IconColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(asset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MembershipsTable,
			Columns: []string{channel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MembershipsTable,
			Columns: []string{channel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.MembershipsTable,
			Columns: []string{channel.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelmembership.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CategoriesTable,
			Columns: []string{channel.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !_u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CategoriesTable,
			Columns: []string{channel.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CategoriesTable,
			Columns: []string{channel.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CollectionsTable,
			Columns: []string{channel.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionsIDs(); len(nodes) > 0 && !_u.mutation.CollectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CollectionsTable,
			Columns: []string{channel.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.CollectionsTable,
			Columns: []string{channel.CollectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PostsTable,
			Columns: []string{channel.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPostsIDs(); len(nodes) > 0 && !_u.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PostsTable,
			Columns: []string{channel.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PostsTable,
			Columns: []string{channel.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.NodesTable,
			Columns: []string{channel.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNodesIDs(); len(nodes) > 0 && !_u.mutation.NodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.NodesTable,
			Columns: []string{channel.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.NodesTable,
			Columns: []string{channel.NodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(node.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
