// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/pollvote"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/rs/xid"
)

// PollVoteCreate is the builder for creating a PollVote entity.
type PollVoteCreate struct {
	config
	mutation *PollVoteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PollVoteCreate) SetCreatedAt(v time.Time) *PollVoteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PollVoteCreate) SetNillableCreatedAt(v *time.Time) *PollVoteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *PollVoteCreate) SetAccountID(v xid.ID) *PollVoteCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetPostID sets the "post_id" field.
func (_c *PollVoteCreate) SetPostID(v xid.ID) *PollVoteCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetOptionID sets the "option_id" field.
func (_c *PollVoteCreate) SetOptionID(v string) *PollVoteCreate {
	_c.mutation.SetOptionID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PollVoteCreate) SetID(v xid.ID) *PollVoteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PollVoteCreate) SetNillableID(v *xid.ID) *PollVoteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *PollVoteCreate) SetAccount(v *Account) *PollVoteCreate {
	return _c.SetAccountID(v.ID)
}

// SetPost sets the "post" edge to the Post entity.
func (_c *PollVoteCreate) SetPost(v *Post) *PollVoteCreate {
	return _c.SetPostID(v.ID)
}

// Mutation returns the PollVoteMutation object of the builder.
func (_c *PollVoteCreate) Mutation() *PollVoteMutation {
	return _c.mutation
}

// Save creates the PollVote in the database.
func (_c *PollVoteCreate) Save(ctx context.Context) (*PollVote, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PollVoteCreate) SaveX(ctx context.Context) *PollVote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollVoteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollVoteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PollVoteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pollvote.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pollvote.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PollVoteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PollVote.created_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "PollVote.account_id"`)}
	}
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PollVote.post_id"`)}
	}
	if _, ok := _c.mutation.OptionID(); !ok {
		return &ValidationError{Name: "option_id", err: errors.New(`ent: missing required field "PollVote.option_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := pollvote.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PollVote.id": %w`, err)}
		}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "PollVote.account"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PollVote.post"`)}
	}
	return nil
}

func (_c *PollVoteCreate) sqlSave(ctx context.Context) (*PollVote, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PollVoteCreate) createSpec() (*PollVote, *sqlgraph.CreateSpec) {
	var (
		_node = &PollVote{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pollvote.Table, sqlgraph.NewFieldSpec(pollvote.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pollvote.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.OptionID(); ok {
		_spec.SetField(pollvote.FieldOptionID, field.TypeString, value)
		_node.OptionID = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollvote.AccountTable,
			Columns: []string{pollvote.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pollvote.PostTable,
			Columns: []string{pollvote.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PollVote.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PollVoteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PollVoteCreate) OnConflict(opts ...sql.ConflictOption) *PollVoteUpsertOne {
	_c.conflict = opts
	return &PollVoteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PollVote.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PollVoteCreate) OnConflictColumns(columns ...string) *PollVoteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PollVoteUpsertOne{
		create: _c,
	}
}

type (
	// PollVoteUpsertOne is the builder for "upsert"-ing
	//  one PollVote node.
	PollVoteUpsertOne struct {
		create *PollVoteCreate
	}

	// PollVoteUpsert is the "OnConflict" setter.
	PollVoteUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *PollVoteUpsert) SetAccountID(v xid.ID) *PollVoteUpsert {
	u.Set(pollvote.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PollVoteUpsert) UpdateAccountID() *PollVoteUpsert {
	u.SetExcluded(pollvote.FieldAccountID)
	return u
}

// SetPostID sets the "post_id" field.
func (u *PollVoteUpsert) SetPostID(v xid.ID) *PollVoteUpsert {
	u.Set(pollvote.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PollVoteUpsert) UpdatePostID() *PollVoteUpsert {
	u.SetExcluded(pollvote.FieldPostID)
	return u
}

// SetOptionID sets the "option_id" field.
func (u *PollVoteUpsert) SetOptionID(v string) *PollVoteUpsert {
	u.Set(pollvote.FieldOptionID, v)
	return u
}

// UpdateOptionID sets the "option_id" field to the value that was provided on create.
func (u *PollVoteUpsert) UpdateOptionID() *PollVoteUpsert {
	u.SetExcluded(pollvote.FieldOptionID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PollVote.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pollvote.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PollVoteUpsertOne) UpdateNewValues() *PollVoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pollvote.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pollvote.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PollVote.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PollVoteUpsertOne) Ignore() *PollVoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PollVoteUpsertOne) DoNothing() *PollVoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PollVoteCreate.OnConflict
// documentation for more info.
func (u *PollVoteUpsertOne) Update(set func(*PollVoteUpsert)) *PollVoteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PollVoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *PollVoteUpsertOne) SetAccountID(v xid.ID) *PollVoteUpsertOne {
	return u.Update(func(s *PollVoteUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PollVoteUpsertOne) UpdateAccountID() *PollVoteUpsertOne {
	return u.Update(func(s *PollVoteUpsert) {
		s.UpdateAccountID()
	})
}

// SetPostID sets the "post_id" field.
func (u *PollVoteUpsertOne) SetPostID(v xid.ID) *PollVoteUpsertOne {
	return u.Update(func(s *PollVoteUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PollVoteUpsertOne) UpdatePostID() *PollVoteUpsertOne {
	return u.Update(func(s *PollVoteUpsert) {
		s.UpdatePostID()
	})
}

// SetOptionID sets the "option_id" field.
func (u *PollVoteUpsertOne) SetOptionID(v string) *PollVoteUpsertOne {
	return u.Update(func(s *PollVoteUpsert) {
		s.SetOptionID(v)
	})
}

// UpdateOptionID sets the "option_id" field to the value that was provided on create.
func (u *PollVoteUpsertOne) UpdateOptionID() *PollVoteUpsertOne {
	return u.Update(func(s *PollVoteUpsert) {
		s.UpdateOptionID()
	})
}

// Exec executes the query.
func (u *PollVoteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PollVoteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PollVoteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PollVoteUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PollVoteUpsertOne.ID is not supported by MySQL driver. Use PollVoteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PollVoteUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PollVoteCreateBulk is the builder for creating many PollVote entities in bulk.
type PollVoteCreateBulk struct {
	config
	err      error
	builders []*PollVoteCreate
	conflict []sql.ConflictOption
}

// Save creates the PollVote entities in the database.
func (_c *PollVoteCreateBulk) Save(ctx context.Context) ([]*PollVote, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PollVote, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PollVoteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PollVoteCreateBulk) SaveX(ctx context.Context) []*PollVote {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollVoteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollVoteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PollVote.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PollVoteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PollVoteCreateBulk) OnConflict(opts ...sql.ConflictOption) *PollVoteUpsertBulk {
	_c.conflict = opts
	return &PollVoteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PollVote.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PollVoteCreateBulk) OnConflictColumns(columns ...string) *PollVoteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PollVoteUpsertBulk{
		create: _c,
	}
}

// PollVoteUpsertBulk is the builder for "upsert"-ing
// a bulk of PollVote nodes.
type PollVoteUpsertBulk struct {
	create *PollVoteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PollVote.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pollvote.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PollVoteUpsertBulk) UpdateNewValues() *PollVoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pollvote.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pollvote.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PollVote.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PollVoteUpsertBulk) Ignore() *PollVoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PollVoteUpsertBulk) DoNothing() *PollVoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PollVoteCreateBulk.OnConflict
// documentation for more info.
func (u *PollVoteUpsertBulk) Update(set func(*PollVoteUpsert)) *PollVoteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PollVoteUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *PollVoteUpsertBulk) SetAccountID(v xid.ID) *PollVoteUpsertBulk {
	return u.Update(func(s *PollVoteUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PollVoteUpsertBulk) UpdateAccountID() *PollVoteUpsertBulk {
	return u.Update(func(s *PollVoteUpsert) {
		s.UpdateAccountID()
	})
}

// SetPostID sets the "post_id" field.
func (u *PollVoteUpsertBulk) SetPostID(v xid.ID) *PollVoteUpsertBulk {
	return u.Update(func(s *PollVoteUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *PollVoteUpsertBulk) UpdatePostID() *PollVoteUpsertBulk {
	return u.Update(func(s *PollVoteUpsert) {
		s.UpdatePostID()
	})
}

// SetOptionID sets the "option_id" field.
func (u *PollVoteUpsertBulk) SetOptionID(v string) *PollVoteUpsertBulk {
	return u.Update(func(s *PollVoteUpsert) {
		s.SetOptionID(v)
	})
}

// UpdateOptionID sets the "option_id" field to the value that was provided on create.
func (u *PollVoteUpsertBulk) UpdateOptionID() *PollVoteUpsertBulk {
	return u.Update(func(s *PollVoteUpsert) {
		s.UpdateOptionID()
	})
}

// Exec executes the query.
func (u *PollVoteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PollVoteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PollVoteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PollVoteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
