// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/postsentiment"
	"github.com/rs/xid"
)

// PostSentiment is the model entity for the PostSentiment schema.
type PostSentiment struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID xid.ID `json:"post_id,omitempty"`
	// Sentiment classification: positive, neutral, negative
	SentimentTag *string `json:"sentiment_tag,omitempty"`
	// Positivity score from 0-100
	PositivityScore *int `json:"positivity_score,omitempty"`
	// Primary topic from allowed list
	PrimaryTopic *string `json:"primary_topic,omitempty"`
	// Status of sentiment scoring: unscored, scored, failed
	ScoringStatus postsentiment.ScoringStatus `json:"scoring_status,omitempty"`
	// Composite ranking score for feed ordering
	RankScore float64 `json:"rank_score,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostSentimentQuery when eager-loading is set.
	Edges        PostSentimentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostSentimentEdges holds the relations/edges for other nodes in the graph.
type PostSentimentEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostSentimentEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostSentiment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case postsentiment.FieldRankScore:
			values[i] = new(sql.NullFloat64)
		case postsentiment.FieldPositivityScore:
			values[i] = new(sql.NullInt64)
		case postsentiment.FieldSentimentTag, postsentiment.FieldPrimaryTopic, postsentiment.FieldScoringStatus:
			values[i] = new(sql.NullString)
		case postsentiment.FieldCreatedAt, postsentiment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case postsentiment.FieldID, postsentiment.FieldPostID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostSentiment fields.
func (_m *PostSentiment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case postsentiment.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case postsentiment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case postsentiment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case postsentiment.FieldPostID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value != nil {
				_m.PostID = *value
			}
		case postsentiment.FieldSentimentTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sentiment_tag", values[i])
			} else if value.Valid {
				_m.SentimentTag = new(string)
				*_m.SentimentTag = value.String
			}
		case postsentiment.FieldPositivityScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field positivity_score", values[i])
			} else if value.Valid {
				_m.PositivityScore = new(int)
				*_m.PositivityScore = int(value.Int64)
			}
		case postsentiment.FieldPrimaryTopic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field primary_topic", values[i])
			} else if value.Valid {
				_m.PrimaryTopic = new(string)
				*_m.PrimaryTopic = value.String
			}
		case postsentiment.FieldScoringStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scoring_status", values[i])
			} else if value.Valid {
				_m.ScoringStatus = postsentiment.ScoringStatus(value.String)
			}
		case postsentiment.FieldRankScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rank_score", values[i])
			} else if value.Valid {
				_m.RankScore = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostSentiment.
// This includes values selected through modifiers, order, etc.
func (_m *PostSentiment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostSentiment entity.
func (_m *PostSentiment) QueryPost() *PostQuery {
	return NewPostSentimentClient(_m.config).QueryPost(_m)
}

// Update returns a builder for updating this PostSentiment.
// Note that you need to call PostSentiment.Unwrap() before calling this method if this PostSentiment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PostSentiment) Update() *PostSentimentUpdateOne {
	return NewPostSentimentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PostSentiment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PostSentiment) Unwrap() *PostSentiment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostSentiment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PostSentiment) String() string {
	var builder strings.Builder
	builder.WriteString("PostSentiment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	if v := _m.SentimentTag; v != nil {
		builder.WriteString("sentiment_tag=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PositivityScore; v != nil {
		builder.WriteString("positivity_score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PrimaryTopic; v != nil {
		builder.WriteString("primary_topic=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("scoring_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScoringStatus))
	builder.WriteString(", ")
	builder.WriteString("rank_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.RankScore))
	builder.WriteByte(')')
	return builder.String()
}

// PostSentiments is a parsable slice of PostSentiment.
type PostSentiments []*PostSentiment
