// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/replyadminqueue"
	"github.com/rs/xid"
)

// ReplyAdminQueue is the model entity for the ReplyAdminQueue schema.
type ReplyAdminQueue struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ReplyID holds the value of the "reply_id" field.
	ReplyID xid.ID `json:"reply_id,omitempty"`
	// ThreadID holds the value of the "thread_id" field.
	ThreadID xid.ID `json:"thread_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID xid.ID `json:"channel_id,omitempty"`
	// ContentSnippet holds the value of the "content_snippet" field.
	ContentSnippet string `json:"content_snippet,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReplyAdminQueueQuery when eager-loading is set.
	Edges        ReplyAdminQueueEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReplyAdminQueueEdges holds the relations/edges for other nodes in the graph.
type ReplyAdminQueueEdges struct {
	// Reply holds the value of the reply edge.
	Reply *Post `json:"reply,omitempty"`
	// Thread holds the value of the thread edge.
	Thread *Post `json:"thread,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ReplyOrErr returns the Reply value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReplyAdminQueueEdges) ReplyOrErr() (*Post, error) {
	if e.Reply != nil {
		return e.Reply, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "reply"}
}

// ThreadOrErr returns the Thread value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReplyAdminQueueEdges) ThreadOrErr() (*Post, error) {
	if e.Thread != nil {
		return e.Thread, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "thread"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReplyAdminQueue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case replyadminqueue.FieldContentSnippet:
			values[i] = new(sql.NullString)
		case replyadminqueue.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case replyadminqueue.FieldID, replyadminqueue.FieldReplyID, replyadminqueue.FieldThreadID, replyadminqueue.FieldChannelID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReplyAdminQueue fields.
func (_m *ReplyAdminQueue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case replyadminqueue.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case replyadminqueue.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case replyadminqueue.FieldReplyID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field reply_id", values[i])
			} else if value != nil {
				_m.ReplyID = *value
			}
		case replyadminqueue.FieldThreadID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field thread_id", values[i])
			} else if value != nil {
				_m.ThreadID = *value
			}
		case replyadminqueue.FieldChannelID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value != nil {
				_m.ChannelID = *value
			}
		case replyadminqueue.FieldContentSnippet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_snippet", values[i])
			} else if value.Valid {
				_m.ContentSnippet = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReplyAdminQueue.
// This includes values selected through modifiers, order, etc.
func (_m *ReplyAdminQueue) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReply queries the "reply" edge of the ReplyAdminQueue entity.
func (_m *ReplyAdminQueue) QueryReply() *PostQuery {
	return NewReplyAdminQueueClient(_m.config).QueryReply(_m)
}

// QueryThread queries the "thread" edge of the ReplyAdminQueue entity.
func (_m *ReplyAdminQueue) QueryThread() *PostQuery {
	return NewReplyAdminQueueClient(_m.config).QueryThread(_m)
}

// Update returns a builder for updating this ReplyAdminQueue.
// Note that you need to call ReplyAdminQueue.Unwrap() before calling this method if this ReplyAdminQueue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReplyAdminQueue) Update() *ReplyAdminQueueUpdateOne {
	return NewReplyAdminQueueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReplyAdminQueue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReplyAdminQueue) Unwrap() *ReplyAdminQueue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReplyAdminQueue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReplyAdminQueue) String() string {
	var builder strings.Builder
	builder.WriteString("ReplyAdminQueue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reply_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReplyID))
	builder.WriteString(", ")
	builder.WriteString("thread_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThreadID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("content_snippet=")
	builder.WriteString(_m.ContentSnippet)
	builder.WriteByte(')')
	return builder.String()
}

// ReplyAdminQueues is a parsable slice of ReplyAdminQueue.
type ReplyAdminQueues []*ReplyAdminQueue
