// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/threadshare"
	"github.com/rs/xid"
)

// ThreadShareCreate is the builder for creating a ThreadShare entity.
type ThreadShareCreate struct {
	config
	mutation *ThreadShareMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ThreadShareCreate) SetCreatedAt(v time.Time) *ThreadShareCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ThreadShareCreate) SetNillableCreatedAt(v *time.Time) *ThreadShareCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ThreadShareCreate) SetDeletedAt(v time.Time) *ThreadShareCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ThreadShareCreate) SetNillableDeletedAt(v *time.Time) *ThreadShareCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPostID sets the "post_id" field.
func (_c *ThreadShareCreate) SetPostID(v xid.ID) *ThreadShareCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ThreadShareCreate) SetChannelID(v xid.ID) *ThreadShareCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ThreadShareCreate) SetAccountID(v xid.ID) *ThreadShareCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *ThreadShareCreate) SetSubtitle(v string) *ThreadShareCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_c *ThreadShareCreate) SetNillableSubtitle(v *string) *ThreadShareCreate {
	if v != nil {
		_c.SetSubtitle(*v)
	}
	return _c
}

// SetPinnedRank sets the "pinned_rank" field.
func (_c *ThreadShareCreate) SetPinnedRank(v int) *ThreadShareCreate {
	_c.mutation.SetPinnedRank(v)
	return _c
}

// SetNillablePinnedRank sets the "pinned_rank" field if the given value is not nil.
func (_c *ThreadShareCreate) SetNillablePinnedRank(v *int) *ThreadShareCreate {
	if v != nil {
		_c.SetPinnedRank(*v)
	}
	return _c
}

// SetPinnedAt sets the "pinned_at" field.
func (_c *ThreadShareCreate) SetPinnedAt(v time.Time) *ThreadShareCreate {
	_c.mutation.SetPinnedAt(v)
	return _c
}

// SetNillablePinnedAt sets the "pinned_at" field if the given value is not nil.
func (_c *ThreadShareCreate) SetNillablePinnedAt(v *time.Time) *ThreadShareCreate {
	if v != nil {
		_c.SetPinnedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ThreadShareCreate) SetID(v xid.ID) *ThreadShareCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ThreadShareCreate) SetNillableID(v *xid.ID) *ThreadShareCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *ThreadShareCreate) SetPost(v *Post) *ThreadShareCreate {
	return _c.SetPostID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ThreadShareCreate) SetChannel(v *Channel) *ThreadShareCreate {
	return _c.SetChannelID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ThreadShareCreate) SetAccount(v *Account) *ThreadShareCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the ThreadShareMutation object of the builder.
func (_c *ThreadShareCreate) Mutation() *ThreadShareMutation {
	return _c.mutation
}

// Save creates the ThreadShare in the database.
func (_c *ThreadShareCreate) Save(ctx context.Context) (*ThreadShare, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThreadShareCreate) SaveX(ctx context.Context) *ThreadShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadShareCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadShareCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ThreadShareCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := threadshare.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Subtitle(); !ok {
		v := threadshare.DefaultSubtitle
		_c.mutation.SetSubtitle(v)
	}
	if _, ok := _c.mutation.PinnedRank(); !ok {
		v := threadshare.DefaultPinnedRank
		_c.mutation.SetPinnedRank(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := threadshare.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThreadShareCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ThreadShare.created_at"`)}
	}
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "ThreadShare.post_id"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ThreadShare.channel_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ThreadShare.account_id"`)}
	}
	if _, ok := _c.mutation.PinnedRank(); !ok {
		return &ValidationError{Name: "pinned_rank", err: errors.New(`ent: missing required field "ThreadShare.pinned_rank"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := threadshare.IDValidator(v.String()); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ThreadShare.id": %w`, err)}
		}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "ThreadShare.post"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ThreadShare.channel"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ThreadShare.account"`)}
	}
	return nil
}

func (_c *ThreadShareCreate) sqlSave(ctx context.Context) (*ThreadShare, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*xid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThreadShareCreate) createSpec() (*ThreadShare, *sqlgraph.CreateSpec) {
	var (
		_node = &ThreadShare{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(threadshare.Table, sqlgraph.NewFieldSpec(threadshare.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(threadshare.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(threadshare.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(threadshare.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.PinnedRank(); ok {
		_spec.SetField(threadshare.FieldPinnedRank, field.TypeInt, value)
		_node.PinnedRank = value
	}
	if value, ok := _c.mutation.PinnedAt(); ok {
		_spec.SetField(threadshare.FieldPinnedAt, field.TypeTime, value)
		_node.PinnedAt = &value
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadshare.PostTable,
			Columns: []string{threadshare.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.ChannelTable,
			Columns: []string{threadshare.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.AccountTable,
			Columns: []string{threadshare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ThreadShare.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThreadShareUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ThreadShareCreate) OnConflict(opts ...sql.ConflictOption) *ThreadShareUpsertOne {
	_c.conflict = opts
	return &ThreadShareUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ThreadShare.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThreadShareCreate) OnConflictColumns(columns ...string) *ThreadShareUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThreadShareUpsertOne{
		create: _c,
	}
}

type (
	// ThreadShareUpsertOne is the builder for "upsert"-ing
	//  one ThreadShare node.
	ThreadShareUpsertOne struct {
		create *ThreadShareCreate
	}

	// ThreadShareUpsert is the "OnConflict" setter.
	ThreadShareUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *ThreadShareUpsert) SetDeletedAt(v time.Time) *ThreadShareUpsert {
	u.Set(threadshare.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdateDeletedAt() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ThreadShareUpsert) ClearDeletedAt() *ThreadShareUpsert {
	u.SetNull(threadshare.FieldDeletedAt)
	return u
}

// SetPostID sets the "post_id" field.
func (u *ThreadShareUpsert) SetPostID(v xid.ID) *ThreadShareUpsert {
	u.Set(threadshare.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdatePostID() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldPostID)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *ThreadShareUpsert) SetChannelID(v xid.ID) *ThreadShareUpsert {
	u.Set(threadshare.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdateChannelID() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldChannelID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ThreadShareUpsert) SetAccountID(v xid.ID) *ThreadShareUpsert {
	u.Set(threadshare.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdateAccountID() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldAccountID)
	return u
}

// SetSubtitle sets the "subtitle" field.
func (u *ThreadShareUpsert) SetSubtitle(v string) *ThreadShareUpsert {
	u.Set(threadshare.FieldSubtitle, v)
	return u
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdateSubtitle() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldSubtitle)
	return u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (u *ThreadShareUpsert) ClearSubtitle() *ThreadShareUpsert {
	u.SetNull(threadshare.FieldSubtitle)
	return u
}

// SetPinnedRank sets the "pinned_rank" field.
func (u *ThreadShareUpsert) SetPinnedRank(v int) *ThreadShareUpsert {
	u.Set(threadshare.FieldPinnedRank, v)
	return u
}

// UpdatePinnedRank sets the "pinned_rank" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdatePinnedRank() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldPinnedRank)
	return u
}

// AddPinnedRank adds v to the "pinned_rank" field.
func (u *ThreadShareUpsert) AddPinnedRank(v int) *ThreadShareUpsert {
	u.Add(threadshare.FieldPinnedRank, v)
	return u
}

// SetPinnedAt sets the "pinned_at" field.
func (u *ThreadShareUpsert) SetPinnedAt(v time.Time) *ThreadShareUpsert {
	u.Set(threadshare.FieldPinnedAt, v)
	return u
}

// UpdatePinnedAt sets the "pinned_at" field to the value that was provided on create.
func (u *ThreadShareUpsert) UpdatePinnedAt() *ThreadShareUpsert {
	u.SetExcluded(threadshare.FieldPinnedAt)
	return u
}

// ClearPinnedAt clears the value of the "pinned_at" field.
func (u *ThreadShareUpsert) ClearPinnedAt() *ThreadShareUpsert {
	u.SetNull(threadshare.FieldPinnedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ThreadShare.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(threadshare.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ThreadShareUpsertOne) UpdateNewValues() *ThreadShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(threadshare.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(threadshare.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ThreadShare.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ThreadShareUpsertOne) Ignore() *ThreadShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThreadShareUpsertOne) DoNothing() *ThreadShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThreadShareCreate.OnConflict
// documentation for more info.
func (u *ThreadShareUpsertOne) Update(set func(*ThreadShareUpsert)) *ThreadShareUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThreadShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ThreadShareUpsertOne) SetDeletedAt(v time.Time) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdateDeletedAt() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ThreadShareUpsertOne) ClearDeletedAt() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPostID sets the "post_id" field.
func (u *ThreadShareUpsertOne) SetPostID(v xid.ID) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdatePostID() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdatePostID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ThreadShareUpsertOne) SetChannelID(v xid.ID) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdateChannelID() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateChannelID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ThreadShareUpsertOne) SetAccountID(v xid.ID) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdateAccountID() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateAccountID()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *ThreadShareUpsertOne) SetSubtitle(v string) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdateSubtitle() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateSubtitle()
	})
}

// ClearSubtitle clears the value of the "subtitle" field.
func (u *ThreadShareUpsertOne) ClearSubtitle() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.ClearSubtitle()
	})
}

// SetPinnedRank sets the "pinned_rank" field.
func (u *ThreadShareUpsertOne) SetPinnedRank(v int) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetPinnedRank(v)
	})
}

// AddPinnedRank adds v to the "pinned_rank" field.
func (u *ThreadShareUpsertOne) AddPinnedRank(v int) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.AddPinnedRank(v)
	})
}

// UpdatePinnedRank sets the "pinned_rank" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdatePinnedRank() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdatePinnedRank()
	})
}

// SetPinnedAt sets the "pinned_at" field.
func (u *ThreadShareUpsertOne) SetPinnedAt(v time.Time) *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetPinnedAt(v)
	})
}

// UpdatePinnedAt sets the "pinned_at" field to the value that was provided on create.
func (u *ThreadShareUpsertOne) UpdatePinnedAt() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdatePinnedAt()
	})
}

// ClearPinnedAt clears the value of the "pinned_at" field.
func (u *ThreadShareUpsertOne) ClearPinnedAt() *ThreadShareUpsertOne {
	return u.Update(func(s *ThreadShareUpsert) {
		s.ClearPinnedAt()
	})
}

// Exec executes the query.
func (u *ThreadShareUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThreadShareCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThreadShareUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ThreadShareUpsertOne) ID(ctx context.Context) (id xid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ThreadShareUpsertOne.ID is not supported by MySQL driver. Use ThreadShareUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ThreadShareUpsertOne) IDX(ctx context.Context) xid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ThreadShareCreateBulk is the builder for creating many ThreadShare entities in bulk.
type ThreadShareCreateBulk struct {
	config
	err      error
	builders []*ThreadShareCreate
	conflict []sql.ConflictOption
}

// Save creates the ThreadShare entities in the database.
func (_c *ThreadShareCreateBulk) Save(ctx context.Context) ([]*ThreadShare, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ThreadShare, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThreadShareMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThreadShareCreateBulk) SaveX(ctx context.Context) []*ThreadShare {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThreadShareCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThreadShareCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ThreadShare.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThreadShareUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ThreadShareCreateBulk) OnConflict(opts ...sql.ConflictOption) *ThreadShareUpsertBulk {
	_c.conflict = opts
	return &ThreadShareUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ThreadShare.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThreadShareCreateBulk) OnConflictColumns(columns ...string) *ThreadShareUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThreadShareUpsertBulk{
		create: _c,
	}
}

// ThreadShareUpsertBulk is the builder for "upsert"-ing
// a bulk of ThreadShare nodes.
type ThreadShareUpsertBulk struct {
	create *ThreadShareCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ThreadShare.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(threadshare.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ThreadShareUpsertBulk) UpdateNewValues() *ThreadShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(threadshare.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(threadshare.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ThreadShare.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ThreadShareUpsertBulk) Ignore() *ThreadShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThreadShareUpsertBulk) DoNothing() *ThreadShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThreadShareCreateBulk.OnConflict
// documentation for more info.
func (u *ThreadShareUpsertBulk) Update(set func(*ThreadShareUpsert)) *ThreadShareUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThreadShareUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ThreadShareUpsertBulk) SetDeletedAt(v time.Time) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdateDeletedAt() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ThreadShareUpsertBulk) ClearDeletedAt() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPostID sets the "post_id" field.
func (u *ThreadShareUpsertBulk) SetPostID(v xid.ID) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdatePostID() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdatePostID()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *ThreadShareUpsertBulk) SetChannelID(v xid.ID) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdateChannelID() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateChannelID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ThreadShareUpsertBulk) SetAccountID(v xid.ID) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdateAccountID() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateAccountID()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *ThreadShareUpsertBulk) SetSubtitle(v string) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdateSubtitle() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdateSubtitle()
	})
}

// ClearSubtitle clears the value of the "subtitle" field.
func (u *ThreadShareUpsertBulk) ClearSubtitle() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.ClearSubtitle()
	})
}

// SetPinnedRank sets the "pinned_rank" field.
func (u *ThreadShareUpsertBulk) SetPinnedRank(v int) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetPinnedRank(v)
	})
}

// AddPinnedRank adds v to the "pinned_rank" field.
func (u *ThreadShareUpsertBulk) AddPinnedRank(v int) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.AddPinnedRank(v)
	})
}

// UpdatePinnedRank sets the "pinned_rank" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdatePinnedRank() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdatePinnedRank()
	})
}

// SetPinnedAt sets the "pinned_at" field.
func (u *ThreadShareUpsertBulk) SetPinnedAt(v time.Time) *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.SetPinnedAt(v)
	})
}

// UpdatePinnedAt sets the "pinned_at" field to the value that was provided on create.
func (u *ThreadShareUpsertBulk) UpdatePinnedAt() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.UpdatePinnedAt()
	})
}

// ClearPinnedAt clears the value of the "pinned_at" field.
func (u *ThreadShareUpsertBulk) ClearPinnedAt() *ThreadShareUpsertBulk {
	return u.Update(func(s *ThreadShareUpsert) {
		s.ClearPinnedAt()
	})
}

// Exec executes the query.
func (u *ThreadShareUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ThreadShareCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThreadShareCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThreadShareUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
