// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/threadshare"
	"github.com/rs/xid"
)

// ThreadShare is the model entity for the ThreadShare schema.
type ThreadShare struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// The root thread being shared into another channel
	PostID xid.ID `json:"post_id,omitempty"`
	// The destination channel the thread is featured in
	ChannelID xid.ID `json:"channel_id,omitempty"`
	// The account that shared the thread
	AccountID xid.ID `json:"account_id,omitempty"`
	// Editorial subtitle shown on the featured card at the destination
	Subtitle string `json:"subtitle,omitempty"`
	// Per-destination pin rank; independent of the post's own pinned_rank
	PinnedRank int `json:"pinned_rank,omitempty"`
	// When the share was pinned in the destination channel
	PinnedAt *time.Time `json:"pinned_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ThreadShareQuery when eager-loading is set.
	Edges        ThreadShareEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ThreadShareEdges holds the relations/edges for other nodes in the graph.
type ThreadShareEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThreadShareEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThreadShareEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThreadShareEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ThreadShare) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case threadshare.FieldPinnedRank:
			values[i] = new(sql.NullInt64)
		case threadshare.FieldSubtitle:
			values[i] = new(sql.NullString)
		case threadshare.FieldCreatedAt, threadshare.FieldDeletedAt, threadshare.FieldPinnedAt:
			values[i] = new(sql.NullTime)
		case threadshare.FieldID, threadshare.FieldPostID, threadshare.FieldChannelID, threadshare.FieldAccountID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ThreadShare fields.
func (_m *ThreadShare) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case threadshare.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case threadshare.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case threadshare.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case threadshare.FieldPostID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value != nil {
				_m.PostID = *value
			}
		case threadshare.FieldChannelID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value != nil {
				_m.ChannelID = *value
			}
		case threadshare.FieldAccountID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value != nil {
				_m.AccountID = *value
			}
		case threadshare.FieldSubtitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subtitle", values[i])
			} else if value.Valid {
				_m.Subtitle = value.String
			}
		case threadshare.FieldPinnedRank:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pinned_rank", values[i])
			} else if value.Valid {
				_m.PinnedRank = int(value.Int64)
			}
		case threadshare.FieldPinnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field pinned_at", values[i])
			} else if value.Valid {
				_m.PinnedAt = new(time.Time)
				*_m.PinnedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ThreadShare.
// This includes values selected through modifiers, order, etc.
func (_m *ThreadShare) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the ThreadShare entity.
func (_m *ThreadShare) QueryPost() *PostQuery {
	return NewThreadShareClient(_m.config).QueryPost(_m)
}

// QueryChannel queries the "channel" edge of the ThreadShare entity.
func (_m *ThreadShare) QueryChannel() *ChannelQuery {
	return NewThreadShareClient(_m.config).QueryChannel(_m)
}

// QueryAccount queries the "account" edge of the ThreadShare entity.
func (_m *ThreadShare) QueryAccount() *AccountQuery {
	return NewThreadShareClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this ThreadShare.
// Note that you need to call ThreadShare.Unwrap() before calling this method if this ThreadShare
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ThreadShare) Update() *ThreadShareUpdateOne {
	return NewThreadShareClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ThreadShare entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ThreadShare) Unwrap() *ThreadShare {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ThreadShare is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ThreadShare) String() string {
	var builder strings.Builder
	builder.WriteString("ThreadShare(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("post_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostID))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("subtitle=")
	builder.WriteString(_m.Subtitle)
	builder.WriteString(", ")
	builder.WriteString("pinned_rank=")
	builder.WriteString(fmt.Sprintf("%v", _m.PinnedRank))
	builder.WriteString(", ")
	if v := _m.PinnedAt; v != nil {
		builder.WriteString("pinned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ThreadShares is a parsable slice of ThreadShare.
type ThreadShares []*ThreadShare
