// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Southclaws/storyden/internal/ent/account"
	"github.com/Southclaws/storyden/internal/ent/channel"
	"github.com/Southclaws/storyden/internal/ent/post"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/Southclaws/storyden/internal/ent/threadshare"
	"github.com/rs/xid"
)

// ThreadShareUpdate is the builder for updating ThreadShare entities.
type ThreadShareUpdate struct {
	config
	hooks     []Hook
	mutation  *ThreadShareMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ThreadShareUpdate builder.
func (_u *ThreadShareUpdate) Where(ps ...predicate.ThreadShare) *ThreadShareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ThreadShareUpdate) SetDeletedAt(v time.Time) *ThreadShareUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillableDeletedAt(v *time.Time) *ThreadShareUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ThreadShareUpdate) ClearDeletedAt() *ThreadShareUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *ThreadShareUpdate) SetPostID(v xid.ID) *ThreadShareUpdate {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillablePostID(v *xid.ID) *ThreadShareUpdate {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ThreadShareUpdate) SetChannelID(v xid.ID) *ThreadShareUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillableChannelID(v *xid.ID) *ThreadShareUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ThreadShareUpdate) SetAccountID(v xid.ID) *ThreadShareUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillableAccountID(v *xid.ID) *ThreadShareUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *ThreadShareUpdate) SetSubtitle(v string) *ThreadShareUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillableSubtitle(v *string) *ThreadShareUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *ThreadShareUpdate) ClearSubtitle() *ThreadShareUpdate {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetPinnedRank sets the "pinned_rank" field.
func (_u *ThreadShareUpdate) SetPinnedRank(v int) *ThreadShareUpdate {
	_u.mutation.ResetPinnedRank()
	_u.mutation.SetPinnedRank(v)
	return _u
}

// SetNillablePinnedRank sets the "pinned_rank" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillablePinnedRank(v *int) *ThreadShareUpdate {
	if v != nil {
		_u.SetPinnedRank(*v)
	}
	return _u
}

// AddPinnedRank adds value to the "pinned_rank" field.
func (_u *ThreadShareUpdate) AddPinnedRank(v int) *ThreadShareUpdate {
	_u.mutation.AddPinnedRank(v)
	return _u
}

// SetPinnedAt sets the "pinned_at" field.
func (_u *ThreadShareUpdate) SetPinnedAt(v time.Time) *ThreadShareUpdate {
	_u.mutation.SetPinnedAt(v)
	return _u
}

// SetNillablePinnedAt sets the "pinned_at" field if the given value is not nil.
func (_u *ThreadShareUpdate) SetNillablePinnedAt(v *time.Time) *ThreadShareUpdate {
	if v != nil {
		_u.SetPinnedAt(*v)
	}
	return _u
}

// ClearPinnedAt clears the value of the "pinned_at" field.
func (_u *ThreadShareUpdate) ClearPinnedAt() *ThreadShareUpdate {
	_u.mutation.ClearPinnedAt()
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *ThreadShareUpdate) SetPost(v *Post) *ThreadShareUpdate {
	return _u.SetPostID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ThreadShareUpdate) SetChannel(v *Channel) *ThreadShareUpdate {
	return _u.SetChannelID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ThreadShareUpdate) SetAccount(v *Account) *ThreadShareUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ThreadShareMutation object of the builder.
func (_u *ThreadShareUpdate) Mutation() *ThreadShareMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *ThreadShareUpdate) ClearPost() *ThreadShareUpdate {
	_u.mutation.ClearPost()
	return _u
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ThreadShareUpdate) ClearChannel() *ThreadShareUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ThreadShareUpdate) ClearAccount() *ThreadShareUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ThreadShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThreadShareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ThreadShareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThreadShareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThreadShareUpdate) check() error {
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ThreadShare.post"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ThreadShare.channel"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ThreadShare.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ThreadShareUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ThreadShareUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ThreadShareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(threadshare.Table, threadshare.Columns, sqlgraph.NewFieldSpec(threadshare.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(threadshare.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(threadshare.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(threadshare.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(threadshare.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.PinnedRank(); ok {
		_spec.SetField(threadshare.FieldPinnedRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPinnedRank(); ok {
		_spec.AddField(threadshare.FieldPinnedRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PinnedAt(); ok {
		_spec.SetField(threadshare.FieldPinnedAt, field.TypeTime, value)
	}
	if _u.mutation.PinnedAtCleared() {
		_spec.ClearField(threadshare.FieldPinnedAt, field.TypeTime)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadshare.PostTable,
			Columns: []string{threadshare.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadshare.PostTable,
			Columns: []string{threadshare.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.ChannelTable,
			Columns: []string{threadshare.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.ChannelTable,
			Columns: []string{threadshare.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.AccountTable,
			Columns: []string{threadshare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.AccountTable,
			Columns: []string{threadshare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{threadshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ThreadShareUpdateOne is the builder for updating a single ThreadShare entity.
type ThreadShareUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ThreadShareMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ThreadShareUpdateOne) SetDeletedAt(v time.Time) *ThreadShareUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillableDeletedAt(v *time.Time) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ThreadShareUpdateOne) ClearDeletedAt() *ThreadShareUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPostID sets the "post_id" field.
func (_u *ThreadShareUpdateOne) SetPostID(v xid.ID) *ThreadShareUpdateOne {
	_u.mutation.SetPostID(v)
	return _u
}

// SetNillablePostID sets the "post_id" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillablePostID(v *xid.ID) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetPostID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *ThreadShareUpdateOne) SetChannelID(v xid.ID) *ThreadShareUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillableChannelID(v *xid.ID) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ThreadShareUpdateOne) SetAccountID(v xid.ID) *ThreadShareUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillableAccountID(v *xid.ID) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *ThreadShareUpdateOne) SetSubtitle(v string) *ThreadShareUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillableSubtitle(v *string) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *ThreadShareUpdateOne) ClearSubtitle() *ThreadShareUpdateOne {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetPinnedRank sets the "pinned_rank" field.
func (_u *ThreadShareUpdateOne) SetPinnedRank(v int) *ThreadShareUpdateOne {
	_u.mutation.ResetPinnedRank()
	_u.mutation.SetPinnedRank(v)
	return _u
}

// SetNillablePinnedRank sets the "pinned_rank" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillablePinnedRank(v *int) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetPinnedRank(*v)
	}
	return _u
}

// AddPinnedRank adds value to the "pinned_rank" field.
func (_u *ThreadShareUpdateOne) AddPinnedRank(v int) *ThreadShareUpdateOne {
	_u.mutation.AddPinnedRank(v)
	return _u
}

// SetPinnedAt sets the "pinned_at" field.
func (_u *ThreadShareUpdateOne) SetPinnedAt(v time.Time) *ThreadShareUpdateOne {
	_u.mutation.SetPinnedAt(v)
	return _u
}

// SetNillablePinnedAt sets the "pinned_at" field if the given value is not nil.
func (_u *ThreadShareUpdateOne) SetNillablePinnedAt(v *time.Time) *ThreadShareUpdateOne {
	if v != nil {
		_u.SetPinnedAt(*v)
	}
	return _u
}

// ClearPinnedAt clears the value of the "pinned_at" field.
func (_u *ThreadShareUpdateOne) ClearPinnedAt() *ThreadShareUpdateOne {
	_u.mutation.ClearPinnedAt()
	return _u
}

// SetPost sets the "post" edge to the Post entity.
func (_u *ThreadShareUpdateOne) SetPost(v *Post) *ThreadShareUpdateOne {
	return _u.SetPostID(v.ID)
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *ThreadShareUpdateOne) SetChannel(v *Channel) *ThreadShareUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ThreadShareUpdateOne) SetAccount(v *Account) *ThreadShareUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ThreadShareMutation object of the builder.
func (_u *ThreadShareUpdateOne) Mutation() *ThreadShareMutation {
	return _u.mutation
}

// ClearPost clears the "post" edge to the Post entity.
func (_u *ThreadShareUpdateOne) ClearPost() *ThreadShareUpdateOne {
	_u.mutation.ClearPost()
	return _u
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *ThreadShareUpdateOne) ClearChannel() *ThreadShareUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ThreadShareUpdateOne) ClearAccount() *ThreadShareUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ThreadShareUpdate builder.
func (_u *ThreadShareUpdateOne) Where(ps ...predicate.ThreadShare) *ThreadShareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ThreadShareUpdateOne) Select(field string, fields ...string) *ThreadShareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ThreadShare entity.
func (_u *ThreadShareUpdateOne) Save(ctx context.Context) (*ThreadShare, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThreadShareUpdateOne) SaveX(ctx context.Context) *ThreadShare {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ThreadShareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThreadShareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThreadShareUpdateOne) check() error {
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ThreadShare.post"`)
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ThreadShare.channel"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ThreadShare.account"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ThreadShareUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ThreadShareUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ThreadShareUpdateOne) sqlSave(ctx context.Context) (_node *ThreadShare, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(threadshare.Table, threadshare.Columns, sqlgraph.NewFieldSpec(threadshare.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ThreadShare.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, threadshare.FieldID)
		for _, f := range fields {
			if !threadshare.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != threadshare.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(threadshare.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(threadshare.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(threadshare.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(threadshare.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.PinnedRank(); ok {
		_spec.SetField(threadshare.FieldPinnedRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPinnedRank(); ok {
		_spec.AddField(threadshare.FieldPinnedRank, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PinnedAt(); ok {
		_spec.SetField(threadshare.FieldPinnedAt, field.TypeTime, value)
	}
	if _u.mutation.PinnedAtCleared() {
		_spec.ClearField(threadshare.FieldPinnedAt, field.TypeTime)
	}
	if _u.mutation.PostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadshare.PostTable,
			Columns: []string{threadshare.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   threadshare.PostTable,
			Columns: []string{threadshare.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.ChannelTable,
			Columns: []string{threadshare.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.ChannelTable,
			Columns: []string{threadshare.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.AccountTable,
			Columns: []string{threadshare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   threadshare.AccountTable,
			Columns: []string{threadshare.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ThreadShare{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{threadshare.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
