// Code generated by ent, DO NOT EDIT.

package pollvote

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Southclaws/storyden/internal/ent/predicate"
	"github.com/rs/xid"
)

// ID filters vertices based on their ID field.
func ID(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldAccountID, v))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldPostID, v))
}

// OptionID applies equality check predicate on the "option_id" field. It's identical to OptionIDEQ.
func OptionID(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldOptionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PollVote {
	return predicate.PollVote(sql.FieldLTE(FieldCreatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldContains(FieldAccountID, vc))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldHasPrefix(FieldAccountID, vc))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldHasSuffix(FieldAccountID, vc))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldEqualFold(FieldAccountID, vc))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldContainsFold(FieldAccountID, vc))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldGT(FieldPostID, v))
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldGTE(FieldPostID, v))
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldLT(FieldPostID, v))
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v xid.ID) predicate.PollVote {
	return predicate.PollVote(sql.FieldLTE(FieldPostID, v))
}

// PostIDContains applies the Contains predicate on the "post_id" field.
func PostIDContains(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldContains(FieldPostID, vc))
}

// PostIDHasPrefix applies the HasPrefix predicate on the "post_id" field.
func PostIDHasPrefix(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldHasPrefix(FieldPostID, vc))
}

// PostIDHasSuffix applies the HasSuffix predicate on the "post_id" field.
func PostIDHasSuffix(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldHasSuffix(FieldPostID, vc))
}

// PostIDEqualFold applies the EqualFold predicate on the "post_id" field.
func PostIDEqualFold(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldEqualFold(FieldPostID, vc))
}

// PostIDContainsFold applies the ContainsFold predicate on the "post_id" field.
func PostIDContainsFold(v xid.ID) predicate.PollVote {
	vc := v.String()
	return predicate.PollVote(sql.FieldContainsFold(FieldPostID, vc))
}

// OptionIDEQ applies the EQ predicate on the "option_id" field.
func OptionIDEQ(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldEQ(FieldOptionID, v))
}

// OptionIDNEQ applies the NEQ predicate on the "option_id" field.
func OptionIDNEQ(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldNEQ(FieldOptionID, v))
}

// OptionIDIn applies the In predicate on the "option_id" field.
func OptionIDIn(vs ...string) predicate.PollVote {
	return predicate.PollVote(sql.FieldIn(FieldOptionID, vs...))
}

// OptionIDNotIn applies the NotIn predicate on the "option_id" field.
func OptionIDNotIn(vs ...string) predicate.PollVote {
	return predicate.PollVote(sql.FieldNotIn(FieldOptionID, vs...))
}

// OptionIDGT applies the GT predicate on the "option_id" field.
func OptionIDGT(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldGT(FieldOptionID, v))
}

// OptionIDGTE applies the GTE predicate on the "option_id" field.
func OptionIDGTE(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldGTE(FieldOptionID, v))
}

// OptionIDLT applies the LT predicate on the "option_id" field.
func OptionIDLT(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldLT(FieldOptionID, v))
}

// OptionIDLTE applies the LTE predicate on the "option_id" field.
func OptionIDLTE(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldLTE(FieldOptionID, v))
}

// OptionIDContains applies the Contains predicate on the "option_id" field.
func OptionIDContains(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldContains(FieldOptionID, v))
}

// OptionIDHasPrefix applies the HasPrefix predicate on the "option_id" field.
func OptionIDHasPrefix(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldHasPrefix(FieldOptionID, v))
}

// OptionIDHasSuffix applies the HasSuffix predicate on the "option_id" field.
func OptionIDHasSuffix(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldHasSuffix(FieldOptionID, v))
}

// OptionIDEqualFold applies the EqualFold predicate on the "option_id" field.
func OptionIDEqualFold(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldEqualFold(FieldOptionID, v))
}

// OptionIDContainsFold applies the ContainsFold predicate on the "option_id" field.
func OptionIDContainsFold(v string) predicate.PollVote {
	return predicate.PollVote(sql.FieldContainsFold(FieldOptionID, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.PollVote {
	return predicate.PollVote(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.PollVote {
	return predicate.PollVote(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.PollVote {
	return predicate.PollVote(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.PollVote {
	return predicate.PollVote(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PollVote) predicate.PollVote {
	return predicate.PollVote(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PollVote) predicate.PollVote {
	return predicate.PollVote(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PollVote) predicate.PollVote {
	return predicate.PollVote(sql.NotPredicates(p))
}
