// Code generated by ent, DO NOT EDIT.

package adminreplytime

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the adminreplytime type in the database.
	Label = "admin_reply_time"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUserPostID holds the string denoting the user_post_id field in the database.
	FieldUserPostID = "user_post_id"
	// FieldAdminPostID holds the string denoting the admin_post_id field in the database.
	FieldAdminPostID = "admin_post_id"
	// FieldUserPostTime holds the string denoting the user_post_time field in the database.
	FieldUserPostTime = "user_post_time"
	// FieldAdminPostTime holds the string denoting the admin_post_time field in the database.
	FieldAdminPostTime = "admin_post_time"
	// FieldAdminAccountID holds the string denoting the admin_account_id field in the database.
	FieldAdminAccountID = "admin_account_id"
	// FieldAdminHandle holds the string denoting the admin_handle field in the database.
	FieldAdminHandle = "admin_handle"
	// FieldTimeDifferenceSeconds holds the string denoting the time_difference_seconds field in the database.
	FieldTimeDifferenceSeconds = "time_difference_seconds"
	// EdgeUserPost holds the string denoting the user_post edge name in mutations.
	EdgeUserPost = "user_post"
	// EdgeAdminPost holds the string denoting the admin_post edge name in mutations.
	EdgeAdminPost = "admin_post"
	// EdgeAdminAccount holds the string denoting the admin_account edge name in mutations.
	EdgeAdminAccount = "admin_account"
	// Table holds the table name of the adminreplytime in the database.
	Table = "admin_reply_times"
	// UserPostTable is the table that holds the user_post relation/edge.
	UserPostTable = "admin_reply_times"
	// UserPostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	UserPostInverseTable = "posts"
	// UserPostColumn is the table column denoting the user_post relation/edge.
	UserPostColumn = "user_post_id"
	// AdminPostTable is the table that holds the admin_post relation/edge.
	AdminPostTable = "admin_reply_times"
	// AdminPostInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	AdminPostInverseTable = "posts"
	// AdminPostColumn is the table column denoting the admin_post relation/edge.
	AdminPostColumn = "admin_post_id"
	// AdminAccountTable is the table that holds the admin_account relation/edge.
	AdminAccountTable = "admin_reply_times"
	// AdminAccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AdminAccountInverseTable = "accounts"
	// AdminAccountColumn is the table column denoting the admin_account relation/edge.
	AdminAccountColumn = "admin_account_id"
)

// Columns holds all SQL columns for adminreplytime fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUserPostID,
	FieldAdminPostID,
	FieldUserPostTime,
	FieldAdminPostTime,
	FieldAdminAccountID,
	FieldAdminHandle,
	FieldTimeDifferenceSeconds,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the AdminReplyTime queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserPostID orders the results by the user_post_id field.
func ByUserPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserPostID, opts...).ToFunc()
}

// ByAdminPostID orders the results by the admin_post_id field.
func ByAdminPostID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminPostID, opts...).ToFunc()
}

// ByUserPostTime orders the results by the user_post_time field.
func ByUserPostTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserPostTime, opts...).ToFunc()
}

// ByAdminPostTime orders the results by the admin_post_time field.
func ByAdminPostTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminPostTime, opts...).ToFunc()
}

// ByAdminAccountID orders the results by the admin_account_id field.
func ByAdminAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminAccountID, opts...).ToFunc()
}

// ByAdminHandle orders the results by the admin_handle field.
func ByAdminHandle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminHandle, opts...).ToFunc()
}

// ByTimeDifferenceSeconds orders the results by the time_difference_seconds field.
func ByTimeDifferenceSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeDifferenceSeconds, opts...).ToFunc()
}

// ByUserPostField orders the results by user_post field.
func ByUserPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserPostStep(), sql.OrderByField(field, opts...))
	}
}

// ByAdminPostField orders the results by admin_post field.
func ByAdminPostField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdminPostStep(), sql.OrderByField(field, opts...))
	}
}

// ByAdminAccountField orders the results by admin_account field.
func ByAdminAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAdminAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newUserPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserPostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserPostTable, UserPostColumn),
	)
}
func newAdminPostStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdminPostInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AdminPostTable, AdminPostColumn),
	)
}
func newAdminAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AdminAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AdminAccountTable, AdminAccountColumn),
	)
}
