/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */
import type { Identifier } from "./identifier";
import type { PaginationQueryParameter } from "./paginationQueryParameter";

export type AdminReplyListParams = {
  /**
   * Pagination query parameters.
   */
  page?: PaginationQueryParameter;
  /**
 * Only return replies authored by this account. When omitted, replies
from all administrators are returned.

 */
  replied_by?: Identifier;
  /**
   * Only return replies created at or after this time.
   */
  created_after?: string;
  /**
   * Only return replies created at or before this time.
   */
  created_before?: string;
};
