/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */

export interface AdminRegenerateTempHandlesResult {
  /** Number of accounts that failed to update in this batch. */
  failed: number;
  /** Cursor to pass as `after` for the next batch. Absent when the table
has been fully drained and no further batches remain.
 */
  next_cursor?: string;
  /** Number of temporary-handle accounts examined in this batch. */
  processed: number;
  /** Number of accounts skipped (no usable name to derive a handle). */
  skipped: number;
  /** Number of handles successfully regenerated in this batch. */
  updated: number;
}
