/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */
import type { ChannelMemberAllOfRole } from "./channelMemberAllOfRole";
import type { Identifier } from "./identifier";
import type { ProfileReference } from "./profileReference";

export type ChannelMemberAllOf = {
  /** The account that is a member */
  account: ProfileReference;
  /** The channel this membership belongs to */
  channel_id: Identifier;
  /** The role of the member in the channel. - owner: Full control, can delete channel - admin: Can manage members and settings - moderator: Can moderate content - member: Basic membership
   */
  role: ChannelMemberAllOfRole;
};
