/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */
import type { Asset } from "./asset";
import type { ChannelAllOfVisibility } from "./channelAllOfVisibility";
import type { Metadata } from "./metadata";

export type ChannelAllOf = {
  cover_image?: Asset;
  /** Description of the channel's purpose */
  description: string;
  icon?: Asset;
  /** Number of members in the channel (includes inflated value for display) */
  member_count?: number;
  meta?: Metadata;
  /** The display name of the channel */
  name: string;
  /** URL-friendly identifier for the channel */
  slug: string;
  /** Channel visibility - public channels are discoverable, private are invite-only */
  visibility: ChannelAllOfVisibility;
};
