/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */
import type { ChannelPersonalizedSimilarGroup } from "./channelPersonalizedSimilarGroup";
import type { ThreadList } from "./threadList";

/**
 * Personalised top-of-feed payload for a channel. self_recent contains
threads created by the requester within the last 24 hours regardless of
visibility. similar contains, for each entry in self_recent, up to two
recent published threads from other users that share the same primary
topic and sentiment tag.

 */
export interface ChannelPersonalizedFeed {
  self_recent: ThreadList;
  similar: ChannelPersonalizedSimilarGroup[];
}
