/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */
import type { ChannelMutablePropsVisibility } from "./channelMutablePropsVisibility";

export interface ChannelMutableProps {
  /**
   * Asset ID for cover image. Set to null to remove.
   * @nullable
   */
  cover_image?: string | null;
  /**
   * Description of the channel's purpose
   * @maxLength 500
   */
  description?: string;
  /**
   * Asset ID for icon. Set to null to remove.
   * @nullable
   */
  icon?: string | null;
  /**
   * The display name of the channel
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /**
   * URL-friendly identifier for the channel
   * @minLength 1
   * @maxLength 100
   * @pattern ^[a-z0-9-]+$
   */
  slug?: string;
  /** Channel visibility */
  visibility?: ChannelMutablePropsVisibility;
}
