/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * storyden
 * Storyden social API for building community driven platforms.
The Storyden API does not adhere to semantic versioning but instead applies a rolling strategy with deprecations and minimal breaking changes. This has been done mainly for a simpler development process and it may be changed to a more fixed versioning strategy in the future. Ultimately, the primary way Storyden tracks versions is dates, there are no set release tags currently.

 * OpenAPI spec version: v1.25.13-canary
 */

/**
 * - draft: Items only accessible by the owner.
- unlisted: Items not publicly listed but reachable via direct link or collection.
- review: Items only accessible by the owner and admins (the moderation queue).
- published: Items published globally and searchable.
- archived: Items dismissed by an admin from the review queue. Hidden from every channel feed; visible only to the original owner.

 */
export type Visibility = (typeof Visibility)[keyof typeof Visibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Visibility = {
  draft: "draft",
  unlisted: "unlisted",
  review: "review",
  published: "published",
  archived: "archived",
} as const;
